using System;
using System.Text;
using WowTools.Core;

namespace WoWPacketViewer
{
    public enum CalendarResponseResult : uint
    {
        CALENDAR_ERROR_GUILD_EVENTS_EXCEEDED = 1,
        CALENDAR_ERROR_EVENTS_EXCEEDED = 2,        // max of 20 (?) exceeded
        CALENDAR_ERROR_SELF_INVITES_EXCEEDED = 3,
        CALENDAR_ERROR_OTHER_INVITES_EXCEEDED = 4,        // std::string
        CALENDAR_ERROR_PERMISSIONS = 5,
        CALENDAR_ERROR_EVENT_INVALID = 6,        // Event not found.
        CALENDAR_ERROR_NOT_INVITED = 7,
        CALENDAR_ERROR_INTERNAL = 8,
        CALENDAR_ERROR_GUILD_PLAYER_NOT_IN_GUILD = 9,
        CALENDAR_ERROR_ALREADY_INVITED_TO_EVENT_S = 10,       // std::string
        CALENDAR_ERROR_PLAYER_NOT_FOUND = 11,
        CALENDAR_ERROR_NOT_ALLIED = 12,
        CALENDAR_ERROR_IGNORING_YOU_S = 13,       // std::string
        CALENDAR_ERROR_INVITES_EXCEEDED = 14,
        // 15 ?
        CALENDAR_ERROR_INVALID_DATE = 16,
        CALENDAR_ERROR_INVALID_TIME = 17,
        // 18 ?
        CALENDAR_ERROR_NEEDS_TITLE = 19,
        CALENDAR_ERROR_EVENT_PASSED = 20,
        CALENDAR_ERROR_EVENT_LOCKED = 21,
        CALENDAR_ERROR_DELETE_CREATOR_FAILED = 22,
        CALENDAR_ERROR_SYSTEM_DISABLED = 24,
        CALENDAR_ERROR_RESTRICTED_ACCOUNT = 25,
        CALENDAR_ERROR_ARENA_EVENTS_EXCEEDED = 26,
        CALENDAR_ERROR_RESTRICTED_LEVEL = 27,
        CALENDAR_ERROR_USER_SQUELCHED = 28,
        CALENDAR_ERROR_NO_INVITE = 29,
        // 30-35 ?
        CALENDAR_ERROR_EVENT_WRONG_SERVER = 36,
        CALENDAR_ERROR_INVITE_WRONG_SERVER = 37,
        CALENDAR_ERROR_NO_GUILD_INVITES = 38,
        CALENDAR_ERROR_INVALID_SIGNUP = 39,
        CALENDAR_ERROR_NO_MODERATOR = 40,
    };
}