namespace WowTools.Core
{
    public enum OpCodes
    {
        MSG_OPCODE_UNKNOWN = 0x10000,    // enum values start over 0xFFFF to avoid overlaps with real opcode numbers
        CMSG_ACCEPT_LEVEL_GRANT,
        CMSG_ACCEPT_TRADE,
        CMSG_ACTIVATETAXI,
        CMSG_ACTIVATETAXIEXPRESS,
        CMSG_ACTIVE_PVP_CHEAT,
        CMSG_ADD_FRIEND,
        CMSG_ADD_IGNORE,
        CMSG_ADD_PVP_MEDAL_CHEAT,
        CMSG_ADD_VOICE_IGNORE,
        CMSG_ALTER_APPEARANCE,
        CMSG_AREATRIGGER,
        CMSG_AREA_SPIRIT_HEALER_QUERY,
        CMSG_AREA_SPIRIT_HEALER_QUEUE,
        CMSG_ARENA_TEAM_ACCEPT,
        CMSG_ARENA_TEAM_CREATE,
        CMSG_ARENA_TEAM_DECLINE,
        CMSG_ARENA_TEAM_DISBAND,
        CMSG_ARENA_TEAM_INVITE,
        CMSG_ARENA_TEAM_LEADER,
        CMSG_ARENA_TEAM_LEAVE,
        CMSG_ARENA_TEAM_QUERY,
        CMSG_ARENA_TEAM_REMOVE,
        CMSG_ARENA_TEAM_ROSTER,
        CMSG_ATTACKSTOP,
        CMSG_ATTACKSWING,
        CMSG_AUCTION_LIST_BIDDER_ITEMS,
        CMSG_AUCTION_LIST_ITEMS,
        CMSG_AUCTION_LIST_OWNER_ITEMS,
        CMSG_AUCTION_LIST_PENDING_SALES,
        CMSG_AUCTION_PLACE_BID,
        CMSG_AUCTION_REMOVE_ITEM,
        CMSG_AUCTION_SELL_ITEM,
        CMSG_AUTH_SESSION,
        CMSG_AUTOBANK_ITEM,
        CMSG_AUTOEQUIP_GROUND_ITEM,
        CMSG_AUTOEQUIP_ITEM,
        CMSG_AUTOEQUIP_ITEM_SLOT,
        CMSG_AUTOSTORE_BAG_ITEM,
        CMSG_AUTOSTORE_BANK_ITEM,
        CMSG_AUTOSTORE_GROUND_ITEM,
        CMSG_AUTOSTORE_LOOT_ITEM,
        CMSG_AUTO_DECLINE_GUILD_INVITES,
        CMSG_BANKER_ACTIVATE,
        CMSG_BATTLEFIELD_JOIN,
        CMSG_BATTLEFIELD_LIST,
        CMSG_BATTLEFIELD_MGR_ENTRY_INVITE_RESPONSE,
        CMSG_BATTLEFIELD_MGR_EXIT_REQUEST,
        CMSG_BATTLEFIELD_MGR_QUEUE_INVITE_RESPONSE,
        CMSG_BATTLEFIELD_MGR_QUEUE_REQUEST,
        CMSG_BATTLEFIELD_PORT,
        CMSG_BATTLEFIELD_REQUEST_SCORE_DATA,
        CMSG_BATTLEFIELD_STATUS,
        CMSG_BATTLEGROUND_PLAYER_POSITIONS,
        CMSG_BATTLEMASTER_HELLO,
        CMSG_BATTLEMASTER_JOIN,
        CMSG_BATTLEMASTER_JOIN_ARENA,
        CMSG_BATTLEMASTER_JOIN_RATED,
        CMSG_BEGIN_TRADE,
        CMSG_BINDER_ACTIVATE,
        CMSG_BOT_DETECTED,
        CMSG_BOT_DETECTED2,
        CMSG_BUG,
        CMSG_BUSY_TRADE,
        CMSG_BUYBACK_ITEM,
        CMSG_BUY_BANK_SLOT,
        CMSG_BUY_ITEM,
        CMSG_BUY_LOTTERY_TICKET_OBSOLETE,
        CMSG_CALENDAR_ADD_EVENT,
        CMSG_CALENDAR_ARENA_TEAM,
        CMSG_CALENDAR_COMPLAIN,
        CMSG_CALENDAR_CONTEXT_EVENT_SIGNUP,
        CMSG_CALENDAR_COPY_EVENT,
        CMSG_CALENDAR_EVENT_INVITE,
        CMSG_CALENDAR_EVENT_MODERATOR_STATUS,
        CMSG_CALENDAR_EVENT_REMOVE_INVITE,
        CMSG_CALENDAR_EVENT_RSVP,
        CMSG_CALENDAR_EVENT_STATUS,
        CMSG_CALENDAR_GET_CALENDAR,
        CMSG_CALENDAR_GET_EVENT,
        CMSG_CALENDAR_GET_NUM_PENDING,
        CMSG_CALENDAR_GUILD_FILTER,
        CMSG_CALENDAR_REMOVE_EVENT,
        CMSG_CALENDAR_UPDATE_EVENT,
        CMSG_CANCEL_AURA,
        CMSG_CANCEL_AUTO_REPEAT_SPELL,
        CMSG_CANCEL_CAST,
        CMSG_CANCEL_CHANNELLING,
        CMSG_CANCEL_GROWTH_AURA,
        CMSG_CANCEL_MOUNT_AURA,
        CMSG_CANCEL_TEMP_ENCHANTMENT,
        CMSG_CANCEL_TRADE,
        CMSG_CAST_SPELL,
        CMSG_CHANGE_PERSONAL_ARENA_RATING,
        CMSG_CHANGE_SEATS_ON_CONTROLLED_VEHICLE,
        CMSG_CHANNEL_ANNOUNCEMENTS,
        CMSG_CHANNEL_BAN,
        CMSG_CHANNEL_DISPLAY_LIST,
        CMSG_CHANNEL_INVITE,
        CMSG_CHANNEL_KICK,
        CMSG_CHANNEL_LIST,
        CMSG_CHANNEL_MODERATE,
        CMSG_CHANNEL_MODERATOR,
        CMSG_CHANNEL_MUTE,
        CMSG_CHANNEL_OWNER,
        CMSG_CHANNEL_PASSWORD,
        CMSG_CHANNEL_ROSTER_INFO,
        CMSG_CHANNEL_SET_OWNER,
        CMSG_CHANNEL_SILENCE_ALL,
        CMSG_CHANNEL_SILENCE_VOICE,
        CMSG_CHANNEL_UNBAN,
        CMSG_CHANNEL_UNMODERATOR,
        CMSG_CHANNEL_UNMUTE,
        CMSG_CHANNEL_UNSILENCE_ALL,
        CMSG_CHANNEL_UNSILENCE_VOICE,
        CMSG_CHANNEL_VOICE_OFF,
        CMSG_CHANNEL_VOICE_ON,
        CMSG_CHARACTER_POINT_CHEAT,
        CMSG_CHAR_CREATE,
        CMSG_CHAR_CUSTOMIZE,
        CMSG_CHAR_DELETE,
        CMSG_CHAR_ENUM,
        CMSG_CHAR_FACTION_CHANGE,
        CMSG_CHAR_RACE_CHANGE,
        CMSG_CHAR_RENAME,
        CMSG_CHAT_FILTERED,
        CMSG_CHAT_IGNORED,
        CMSG_CHEAT_DUMP_ITEMS_DEBUG_ONLY,
        CMSG_CHEAT_PLAYER_LOGIN,
        CMSG_CHEAT_PLAYER_LOOKUP,
        CMSG_CHEAT_SET_ARENA_CURRENCY,
        CMSG_CHEAT_SET_HONOR_CURRENCY,
        CMSG_CHECK_LOGIN_CRITERIA,
        CMSG_CLEAR_CHANNEL_WATCH,
        CMSG_CLEAR_EXPLORATION,
        CMSG_CLEAR_SERVER_BUCK_DATA,
        CMSG_CLEAR_TRADE_ITEM,
        CMSG_COMMENTATOR_ENABLE,
        CMSG_COMMENTATOR_ENTER_INSTANCE,
        CMSG_COMMENTATOR_EXIT_INSTANCE,
        CMSG_COMMENTATOR_GET_MAP_INFO,
        CMSG_COMMENTATOR_GET_PLAYER_INFO,
        CMSG_COMMENTATOR_INSTANCE_COMMAND,
        CMSG_COMMENTATOR_SKIRMISH_QUEUE_COMMAND,
        CMSG_COMMENTATOR_START_WARGAME,
        CMSG_COMPLAIN,
        CMSG_COMPLETE_ACHIEVEMENT_CHEAT,
        CMSG_COMPLETE_CINEMATIC,
        CMSG_COMPLETE_MOVIE,
        CMSG_CONTACT_LIST,
        CMSG_CORPSE_MAP_POSITION_QUERY,
        CMSG_CREATURE_QUERY,
        CMSG_DANCE_QUERY,
        CMSG_DEBUG_ACTIONS_START,
        CMSG_DEBUG_ACTIONS_STOP,
        CMSG_DEBUG_LIST_TARGETS,
        CMSG_DECHARGE,
        CMSG_DECLINE_CHANNEL_INVITE,
        CMSG_DELETE_DANCE,
        CMSG_DEL_FRIEND,
        CMSG_DEL_IGNORE,
        CMSG_DEL_PVP_MEDAL_CHEAT,
        CMSG_DEL_VOICE_IGNORE,
        CMSG_DESTROYITEM,
        CMSG_DESTROY_ITEMS,
        CMSG_DISMISS_CONTROLLED_VEHICLE,
        CMSG_DISMISS_CRITTER,
        CMSG_DUEL_ACCEPTED,
        CMSG_DUEL_CANCELLED,
        CMSG_DUMP_OBJECTS,
        CMSG_EJECT_PASSENGER,
        CMSG_EMOTE,
        CMSG_ENABLETAXI,
        CMSG_ENABLE_DAMAGE_LOG,
        CMSG_EQUIPMENT_SET_DELETE,
        CMSG_EQUIPMENT_SET_SAVE,
        CMSG_EQUIPMENT_SET_USE,
        CMSG_EXPIRE_RAID_INSTANCE,
        CMSG_FAR_SIGHT,
        CMSG_FLOOD_GRACE_CHEAT,
        CMSG_FORCE_FLIGHT_BACK_SPEED_CHANGE_ACK,
        CMSG_FORCE_FLIGHT_SPEED_CHANGE_ACK,
        CMSG_FORCE_MOVE_ROOT_ACK,
        CMSG_FORCE_MOVE_UNROOT_ACK,
        CMSG_FORCE_PITCH_RATE_CHANGE_ACK,
        CMSG_FORCE_RUN_BACK_SPEED_CHANGE_ACK,
        CMSG_FORCE_RUN_SPEED_CHANGE_ACK,
        CMSG_FORCE_SAY_CHEAT,
        CMSG_FORCE_SWIM_BACK_SPEED_CHANGE_ACK,
        CMSG_FORCE_SWIM_SPEED_CHANGE_ACK,
        CMSG_FORCE_TURN_RATE_CHANGE_ACK,
        CMSG_FORCE_UNK1_SPEED_CHANGE_ACK,
        CMSG_FORCE_UNK2_SPEED_CHANGE_ACK,
        CMSG_FORCE_WALK_SPEED_CHANGE_ACK,
        CMSG_GAMEOBJECT_QUERY,
        CMSG_GAMEOBJ_REPORT_USE,
        CMSG_GAMEOBJ_USE,
        CMSG_GAMESPEED_SET,
        CMSG_GAMETIME_SET,
        CMSG_GETDEATHBINDZONE,
        CMSG_GET_CHANNEL_MEMBER_COUNT,
        CMSG_GET_MAIL_LIST,
        CMSG_GET_MIRRORIMAGE_DATA,
        CMSG_GHOST,
        CMSG_GMRESPONSE_RESOLVE,
        CMSG_GMSURVEY_SUBMIT,
        CMSG_GMTICKETSYSTEM_TOGGLE,
        CMSG_GMTICKET_CREATE,
        CMSG_GMTICKET_DELETETICKET,
        CMSG_GMTICKET_GETTICKET,
        CMSG_GMTICKET_SYSTEMSTATUS,
        CMSG_GMTICKET_UPDATETEXT,
        CMSG_GM_CHARACTER_RESTORE,
        CMSG_GM_CHARACTER_SAVE,
        CMSG_GM_CREATE_ITEM_TARGET,
        CMSG_GM_DESTROY_ONLINE_CORPSE,
        CMSG_GM_INVIS,
        CMSG_GM_NUKE,
        CMSG_GM_NUKE_ACCOUNT,
        CMSG_GM_REPORT_LAG,
        CMSG_GM_SET_SECURITY_GROUP,
        CMSG_GM_SHOW_COMPLAINTS,
        CMSG_GM_TEACH,
        CMSG_GM_UNSQUELCH,
        CMSG_GM_UNTEACH,
        CMSG_GM_UPDATE_TICKET_STATUS,
        CMSG_GM_WHISPER,
        CMSG_GOSSIP_HELLO,
        CMSG_GOSSIP_SELECT_OPTION,
        CMSG_GRANT_LEVEL,
        CMSG_GROUP_ACCEPT,
        CMSG_GROUP_ASSISTANT_LEADER,
        CMSG_GROUP_CANCEL,
        CMSG_GROUP_CHANGE_SUB_GROUP,
        CMSG_GROUP_DECLINE,
        CMSG_GROUP_DISBAND,
        CMSG_GROUP_INVITE,
        CMSG_GROUP_RAID_CONVERT,
        CMSG_GROUP_SET_LEADER,
        CMSG_GROUP_SET_ROLES,
        CMSG_GROUP_SWAP_SUB_GROUP,
        CMSG_GROUP_UNINVITE,
        CMSG_GROUP_UNINVITE_GUID,
        CMSG_GUILD_ACCEPT,
        CMSG_GUILD_ADD_RANK,
        CMSG_GUILD_BANKER_ACTIVATE,
        CMSG_GUILD_BANK_BUY_TAB,
        CMSG_GUILD_BANK_DEPOSIT_MONEY,
        CMSG_GUILD_BANK_NOTE,
        CMSG_GUILD_BANK_QUERY_TAB,
        CMSG_GUILD_BANK_SWAP_ITEMS,
        CMSG_GUILD_BANK_UPDATE_TAB,
        CMSG_GUILD_BANK_WITHDRAW_MONEY,
        CMSG_GUILD_CREATE,
        CMSG_GUILD_DECLINE,
        CMSG_GUILD_DEL_RANK,
        CMSG_GUILD_DEMOTE,
        CMSG_GUILD_DISBAND,
        CMSG_GUILD_INFO,
        CMSG_GUILD_INFO_TEXT,
        CMSG_GUILD_INVITE,
        CMSG_GUILD_LEADER,
        CMSG_GUILD_LEAVE,
        CMSG_GUILD_MOTD,
        CMSG_GUILD_PROMOTE,
        CMSG_GUILD_QUERY,
        CMSG_GUILD_RANK,
        CMSG_GUILD_REMOVE,
        CMSG_GUILD_ROSTER,
        CMSG_GUILD_SET_NOTE,
        CMSG_GUILD_SWITCH_RANK,
        CMSG_HEARTH_AND_RESURRECT,
        CMSG_IGNORE_DIMINISHING_RETURNS_CHEAT,
        CMSG_IGNORE_KNOCKBACK_CHEAT,
        CMSG_IGNORE_REQUIREMENTS_CHEAT,
        CMSG_IGNORE_TRADE,
        CMSG_INITIATE_TRADE,
        CMSG_INSPECT,
        CMSG_INSPECT_HONOR_STATS,
        CMSG_INSTANCE_LOCK_WARNING_RESPONSE,
        CMSG_ITEM_NAME_QUERY,
        CMSG_ITEM_REFUND,
        CMSG_ITEM_REFUND_INFO,
        CMSG_ITEM_TEXT_QUERY,
        CMSG_JOIN_CHANNEL,
        CMSG_KEEP_ALIVE,
        CMSG_LEARN_DANCE_MOVE,
        CMSG_LEARN_PREVIEW_TALENTS,
        CMSG_LEARN_PREVIEW_TALENTS_PET,
        CMSG_LEARN_TALENT,
        CMSG_LEAVE_BATTLEFIELD,
        CMSG_LEAVE_CHANNEL,
        CMSG_LFD_PARTY_LOCK_INFO_REQUEST,
        CMSG_LFD_PLAYER_LOCK_INFO_REQUEST,
        CMSG_LFG_JOIN,
        CMSG_LFG_LEAVE,
        CMSG_LFG_PROPOSAL_RESULT,
        CMSG_LFG_SET_BOOT_VOTE,
        CMSG_LFG_SET_NEEDS,
        CMSG_LFG_SET_ROLES,
        CMSG_LFG_SET_ROLES_2,
        CMSG_LFG_TELEPORT,
        CMSG_LIST_INVENTORY,
        CMSG_LOAD_DANCES,
        CMSG_LOADING_SCREEN_NOTIFY,
        CMSG_LOGOUT_CANCEL,
        CMSG_LOGOUT_REQUEST,
        CMSG_LOOT,
        CMSG_LOOT_MASTER_GIVE,
        CMSG_LOOT_METHOD,
        CMSG_LOOT_MONEY,
        CMSG_LOOT_RELEASE,
        CMSG_LOOT_ROLL,
        CMSG_LOTTERY_QUERY_OBSOLETE,
        CMSG_LUA_USAGE,
        CMSG_MAELSTROM_GM_SENT_MAIL,
        CMSG_MAELSTROM_INVALIDATE_CACHE,
        CMSG_MAELSTROM_RENAME_GUILD,
        CMSG_MAIL_CREATE_TEXT_ITEM,
        CMSG_MAIL_DELETE,
        CMSG_MAIL_MARK_AS_READ,
        CMSG_MAIL_RETURN_TO_SENDER,
        CMSG_MAIL_TAKE_ITEM,
        CMSG_MAIL_TAKE_MONEY,
        CMSG_MEETINGSTONE_CHEAT,
        CMSG_MEETINGSTONE_INFO,
        CMSG_MESSAGECHAT_AFK,
        CMSG_MESSAGECHAT_BATTLEGROUND,
        CMSG_MESSAGECHAT_BATTLEGROUND_LEADER,
        CMSG_MESSAGECHAT_CHANNEL,
        CMSG_MESSAGECHAT_DND,
        CMSG_MESSAGECHAT_EMOTE,
        CMSG_MESSAGECHAT_GUILD,
        CMSG_MESSAGECHAT_OFFICER,
        CMSG_MESSAGECHAT_PARTY,
        CMSG_MESSAGECHAT_PARTY_LEADER,
        CMSG_MESSAGECHAT_RAID,
        CMSG_MESSAGECHAT_RAID_LEADER,
        CMSG_MESSAGECHAT_RAID_WARNING,
        CMSG_MESSAGECHAT_SAY,
        CMSG_MESSAGECHAT_WHISPER,
        CMSG_MESSAGECHAT_YELL,
        CMSG_MINIGAME_MOVE,
        CMSG_MOUNTSPECIAL_ANIM,
        CMSG_MOVE_CHNG_TRANSPORT,
        CMSG_MOVE_FALL_RESET,
        CMSG_MOVE_FEATHER_FALL_ACK,
        CMSG_MOVE_FLIGHT_ACK,
        CMSG_MOVE_HOVER_ACK,
        CMSG_MOVE_KNOCK_BACK_ACK,
        CMSG_MOVE_NOT_ACTIVE_MOVER,
        CMSG_MOVE_SET_CAN_FLY_ACK,
        CMSG_MOVE_SET_FLY,
        CMSG_MOVE_SET_RAW_POSITION,
        CMSG_MOVE_SET_RUN_SPEED,
        CMSG_MOVE_SPLINE_DONE,
        CMSG_MOVE_START_SWIM_CHEAT,
        CMSG_MOVE_STOP_SWIM_CHEAT,
        CMSG_MOVE_TIME_SKIPPED,
        CMSG_MOVE_WATER_WALK_ACK,
        CMSG_NAME_QUERY,
        CMSG_NEW_SPELL_SLOT,
        CMSG_NEXT_CINEMATIC_CAMERA,
        CMSG_NO_SPELL_VARIANCE,
        CMSG_NPC_TEXT_QUERY,
        CMSG_OFFER_PETITION,
        CMSG_OPENING_CINEMATIC,
        CMSG_OPEN_ITEM,
        CMSG_OPT_OUT_OF_LOOT,
        CMSG_PAGE_TEXT_QUERY,
        CMSG_PARTY_SILENCE,
        CMSG_PARTY_UNSILENCE,
        CMSG_PETITION_BUY,
        CMSG_PETITION_QUERY,
        CMSG_PETITION_SHOWLIST,
        CMSG_PETITION_SHOW_SIGNATURES,
        CMSG_PETITION_SIGN,
        CMSG_PET_ABANDON,
        CMSG_PET_ACTION,
        CMSG_PET_CANCEL_AURA,
        CMSG_PET_CAST_SPELL,
        CMSG_PET_LEARN_TALENT,
        CMSG_PET_NAME_QUERY,
        CMSG_PET_RENAME,
        CMSG_PET_SET_ACTION,
        CMSG_PET_SPELL_AUTOCAST,
        CMSG_PET_STOP_ATTACK,
        CMSG_PET_UNLEARN,
        CMSG_PET_UNLEARN_TALENTS,
        CMSG_PING,
        CMSG_PLAYED_TIME,
        CMSG_PLAYER_AI_CHEAT,
        CMSG_PLAYER_DIFFICULTY_CHANGE,
        CMSG_PLAYER_LOGIN,
        CMSG_PLAYER_LOGOUT,
        CMSG_PLAYER_VEHICLE_ENTER,
        CMSG_PLAY_DANCE,
        CMSG_PUSHQUESTTOPARTY,
        CMSG_QUERY_GUILD_MAX_XP,
        CMSG_QUERY_GUILD_REWARDS,
        CMSG_QUERY_GUILD_XP,
        CMSG_QUERY_INSPECT_ACHIEVEMENTS,
        CMSG_QUERY_QUESTS_COMPLETED,
        CMSG_QUERY_SERVER_BUCK_DATA,
        CMSG_QUERY_TIME,
        CMSG_QUERY_VEHICLE_STATUS,
        CMSG_QUESTGIVER_ACCEPT_QUEST,
        CMSG_QUESTGIVER_CANCEL,
        CMSG_QUESTGIVER_CHOOSE_REWARD,
        CMSG_QUESTGIVER_COMPLETE_QUEST,
        CMSG_QUESTGIVER_HELLO,
        CMSG_QUESTGIVER_QUERY_QUEST,
        CMSG_QUESTGIVER_QUEST_AUTOLAUNCH,
        CMSG_QUESTGIVER_REQUEST_REWARD,
        CMSG_QUESTGIVER_STATUS_MULTIPLE_QUERY,
        CMSG_QUESTGIVER_STATUS_QUERY,
        CMSG_QUESTLOG_REMOVE_QUEST,
        CMSG_QUESTLOG_SWAP_QUEST,
        CMSG_QUEST_CONFIRM_ACCEPT,
        CMSG_QUEST_POI_QUERY,
        CMSG_QUEST_QUERY,
        CMSG_READY_FOR_ACCOUNT_DATA_TIMES,
        CMSG_READ_ITEM,
        CMSG_REALM_SPLIT,
        CMSG_RECLAIM_CORPSE,
        CMSG_REDIRECTION_AUTH_PROOF,
        CMSG_REDIRECTION_FAILED,
        CMSG_REDIRECT_AUTH_PROOF,
        CMSG_REFER_A_FRIEND,
        CMSG_REMOVE_GLYPH,
        CMSG_REPAIR_ITEM,
        CMSG_REPOP_REQUEST,
        CMSG_REPORT_PVP_AFK,
        CMSG_REQUEST_ACCOUNT_DATA,
        CMSG_REQUEST_PARTY_MEMBER_STATS,
        CMSG_REQUEST_PET_INFO,
        CMSG_REQUEST_PLAYER_VEHICLE_EXIT,
        CMSG_REQUEST_PVP_OPTIONS_ENABLED,
        CMSG_REQUEST_RAID_INFO,
        CMSG_REQUEST_RATED_BG_INFO,
        CMSG_REQUEST_VEHICLE_EXIT,
        CMSG_REQUEST_VEHICLE_NEXT_SEAT,
        CMSG_REQUEST_VEHICLE_PREV_SEAT,
        CMSG_REQUEST_VEHICLE_SWITCH_SEAT,
        CMSG_RESET_FACTION_CHEAT,
        CMSG_RESET_INSTANCES,
        CMSG_RESURRECT_RESPONSE,
        CMSG_RETURN_TO_GRAVEYARD,
        CMSG_RUN_SCRIPT,
        CMSG_SAVE_DANCE,
        CMSG_SAVE_PLAYER,
        CMSG_SEARCH_LFG_JOIN,
        CMSG_SEARCH_LFG_LEAVE,
        CMSG_SELF_RES,
        CMSG_SELL_ITEM,
        CMSG_SEND_COMBAT_TRIGGER,
        CMSG_SEND_GENERAL_TRIGGER,
        CMSG_SEND_LOCAL_EVENT,
        CMSG_SEND_MAIL,
        CMSG_SERVERTIME,
        CMSG_SERVER_BROADCAST,
        CMSG_SERVER_INFO_QUERY,
        CMSG_SETDEATHBINDPOINT,
        CMSG_SETSHEATHED,
        CMSG_SET_ACTIONBAR_TOGGLES,
        CMSG_SET_ACTION_BUTTON,
        CMSG_SET_ACTIVE_MOVER,
        CMSG_SET_ACTIVE_VOICE_CHANNEL,
        CMSG_SET_ALLOW_LOW_LEVEL_RAID1,
        CMSG_SET_ALLOW_LOW_LEVEL_RAID2,
        CMSG_SET_AMMO,
        CMSG_SET_CHANNEL_WATCH,
        CMSG_SET_CONTACT_NOTES,
        CMSG_SET_CRITERIA_CHEAT,
        CMSG_SET_DURABILITY_CHEAT,
        CMSG_SET_EXPLORATION,
        CMSG_SET_EXPLORATION_ALL,
        CMSG_SET_FACTION_ATWAR,
        CMSG_SET_FACTION_CHEAT,
        CMSG_SET_FACTION_INACTIVE,
        CMSG_SET_GLYPH,
        CMSG_SET_GLYPH_SLOT,
        CMSG_SET_GRANTABLE_LEVELS,
        CMSG_SET_GUILD_BANK_TEXT,
        CMSG_SET_LFG_COMMENT,
        CMSG_SET_PLAYER_DECLINED_NAMES,
        CMSG_SET_PRIMARY_TALENT_TREE,
        CMSG_SET_PVP_RANK_CHEAT,
        CMSG_SET_PVP_TITLE,
        CMSG_SET_RUNE_COOLDOWN,
        CMSG_SET_RUNE_COUNT,
        CMSG_SET_SAVED_INSTANCE_EXTEND,
        CMSG_SET_SELECTION,
        CMSG_SET_SKILL_CHEAT,
        CMSG_SET_TAXI_BENCHMARK_MODE,
        CMSG_SET_TITLE,
        CMSG_SET_TITLE_SUFFIX,
        CMSG_SET_TRADE_GOLD,
        CMSG_SET_TRADE_ITEM,
        CMSG_SET_WATCHED_FACTION,
        CMSG_SHOWING_CLOAK,
        CMSG_SHOWING_HELM,
        CMSG_SKILL_BUY_RANK,
        CMSG_SKILL_BUY_STEP,
        CMSG_SOCKET_GEMS,
        CMSG_SPELLCLICK,
        CMSG_SPIRIT_HEALER_ACTIVATE,
        CMSG_SPLIT_ITEM,
        CMSG_STABLE_CHANGE_SLOT,
        CMSG_STABLE_REVIVE_PET,
        CMSG_STANDSTATECHANGE,
        CMSG_START_QUEST,
        CMSG_STOP_DANCE,
        CMSG_STORE_LOOT_IN_SLOT,
        CMSG_SUMMON_RESPONSE,
        CMSG_SWAP_INV_ITEM,
        CMSG_SWAP_ITEM,
        CMSG_SYNC_DANCE,
        CMSG_TARGET_CAST,
        CMSG_TARGET_SCRIPT_CAST,
        CMSG_TAXICLEARALLNODES,
        CMSG_TAXICLEARNODE,
        CMSG_TAXIENABLEALLNODES,
        CMSG_TAXIENABLENODE,
        CMSG_TAXINODE_STATUS_QUERY,
        CMSG_TAXIQUERYAVAILABLENODES,
        CMSG_TAXISHOWNODES,
        CMSG_TELEPORT_TO_UNIT,
        CMSG_TEXT_EMOTE,
        CMSG_TIME_SYNC_RESP,
        CMSG_TOGGLE_PVP,
        CMSG_TOTEM_DESTROYED,
        CMSG_TRAINER_BUY_SPELL,
        CMSG_TRAINER_LIST,
        CMSG_TRANSFORM,
        CMSG_TRIGGER_CINEMATIC_CHEAT,
        CMSG_TURN_IN_PETITION,
        CMSG_TUTORIAL_CLEAR,
        CMSG_TUTORIAL_FLAG,
        CMSG_TUTORIAL_RESET,
        CMSG_UNACCEPT_TRADE,
        CMSG_UNITANIMTIER_CHEAT,
        CMSG_UNKNOWN_1296,
        CMSG_UNKNOWN_1303,
        CMSG_UNKNOWN_1320,
        CMSG_UNLEARN_DANCE_MOVE,
        CMSG_UNLEARN_SKILL,
        CMSG_UNLEARN_SPELL,
        CMSG_UNLEARN_TALENTS,
        CMSG_UNUSED2,
        CMSG_UPDATE_ACCOUNT_DATA,
        CMSG_UPDATE_MISSILE_TRAJECTORY,
        CMSG_UPDATE_PROJECTILE_POSITION,
        CMSG_USE_ITEM,
        CMSG_VOICE_SESSION_ENABLE,
        CMSG_VOICE_SET_TALKER_MUTED_REQUEST,
        CMSG_WARDEN_DATA,
        CMSG_WHO,
        CMSG_WHOIS,
        CMSG_WORLD_LOGIN,
        CMSG_WORLD_STATE_UI_TIMER_UPDATE,
        CMSG_WORLD_TELEPORT,
        CMSG_WRAP_ITEM,
        CMSG_ZONEUPDATE,
        MSG_AUCTION_HELLO,
        MSG_CHANNEL_START,
        MSG_CHANNEL_UPDATE,
        MSG_CORPSE_QUERY,
        MSG_DELAY_GHOST_TELEPORT,
        MSG_GM_ACCOUNT_ONLINE,
        MSG_GM_BIND_OTHER,
        MSG_GM_CHANGE_ARENA_RATING,
        MSG_GM_DESTROY_CORPSE,
        MSG_GM_GEARRATING,
        MSG_GM_RESETINSTANCELIMIT,
        MSG_GM_SHOWLABEL,
        MSG_GM_SUMMON,
        MSG_GUILD_BANK_LOG_QUERY,
        MSG_GUILD_BANK_MONEY_WITHDRAWN,
        MSG_GUILD_EVENT_LOG_QUERY,
        MSG_GUILD_PERMISSIONS,
        MSG_INSPECT_ARENA_TEAMS,
        MSG_LIST_STABLED_PETS,
        MSG_MINIMAP_PING,
        MSG_MOVE_FALL_LAND,
        MSG_MOVE_FEATHER_FALL,
        MSG_MOVE_HEARTBEAT,
        MSG_MOVE_HOVER,
        MSG_MOVE_JUMP,
        MSG_MOVE_KNOCK_BACK,
        MSG_MOVE_ROOT,
        MSG_MOVE_SET_ALL_SPEED_CHEAT,
        MSG_MOVE_SET_FACING,
        MSG_MOVE_SET_FLIGHT_BACK_SPEED,
        MSG_MOVE_SET_FLIGHT_BACK_SPEED_CHEAT,
        MSG_MOVE_SET_FLIGHT_SPEED,
        MSG_MOVE_SET_FLIGHT_SPEED_CHEAT,
        MSG_MOVE_SET_PITCH,
        MSG_MOVE_SET_PITCH_RATE,
        MSG_MOVE_SET_PITCH_RATE_CHEAT,
        MSG_MOVE_SET_RAW_POSITION_ACK,
        MSG_MOVE_SET_RUN_BACK_SPEED,
        MSG_MOVE_SET_RUN_BACK_SPEED_CHEAT,
        MSG_MOVE_SET_RUN_MODE,
        MSG_MOVE_SET_RUN_SPEED,
        MSG_MOVE_SET_RUN_SPEED_CHEAT,
        MSG_MOVE_SET_SWIM_BACK_SPEED,
        MSG_MOVE_SET_SWIM_BACK_SPEED_CHEAT,
        MSG_MOVE_SET_SWIM_SPEED,
        MSG_MOVE_SET_SWIM_SPEED_CHEAT,
        MSG_MOVE_SET_TURN_RATE,
        MSG_MOVE_SET_TURN_RATE_CHEAT,
        MSG_MOVE_SET_WALK_MODE,
        MSG_MOVE_SET_WALK_SPEED,
        MSG_MOVE_SET_WALK_SPEED_CHEAT,
        MSG_MOVE_START_ASCEND,
        MSG_MOVE_START_BACKWARD,
        MSG_MOVE_START_DESCEND,
        MSG_MOVE_START_FORWARD,
        MSG_MOVE_START_PITCH_DOWN,
        MSG_MOVE_START_PITCH_UP,
        MSG_MOVE_START_STRAFE_LEFT,
        MSG_MOVE_START_STRAFE_RIGHT,
        MSG_MOVE_START_SWIM,
        MSG_MOVE_START_SWIM_CHEAT,
        MSG_MOVE_START_TURN_LEFT,
        MSG_MOVE_START_TURN_RIGHT,
        MSG_MOVE_STOP,
        MSG_MOVE_STOP_ASCEND,
        MSG_MOVE_STOP_PITCH,
        MSG_MOVE_STOP_STRAFE,
        MSG_MOVE_STOP_SWIM,
        MSG_MOVE_STOP_SWIM_CHEAT,
        MSG_MOVE_STOP_TURN,
        MSG_MOVE_TELEPORT,
        MSG_MOVE_TELEPORT_ACK,
        MSG_MOVE_TELEPORT_CHEAT,
        MSG_MOVE_TIME_SKIPPED,
        MSG_MOVE_TOGGLE_COLLISION_CHEAT,
        MSG_MOVE_TOGGLE_FALL_LOGGING,
        MSG_MOVE_TOGGLE_GRAVITY_CHEAT,
        MSG_MOVE_TOGGLE_LOGGING,
        MSG_MOVE_UNROOT,
        MSG_MOVE_UPDATE_CAN_FLY,
        MSG_MOVE_WATER_WALK,
        MSG_MOVE_WORLDPORT_ACK,
        MSG_NOTIFY_PARTY_SQUELCH,
        MSG_PARTY_ASSIGNMENT,
        MSG_PETITION_DECLINE,
        MSG_PETITION_RENAME,
        MSG_PVP_LOG_DATA,
        MSG_QUERY_GUILD_BANK_TEXT,
        MSG_QUERY_NEXT_MAIL_TIME,
        MSG_QUEST_PUSH_RESULT,
        MSG_RAID_READY_CHECK,
        MSG_RAID_READY_CHECK_CONFIRM,
        MSG_RAID_READY_CHECK_FINISHED,
        MSG_RAID_TARGET_UPDATE,
        MSG_RANDOM_ROLL,
        MSG_SAVE_GUILD_EMBLEM,
        MSG_SET_DUNGEON_DIFFICULTY,
        MSG_SET_RAID_DIFFICULTY,
        MSG_TABARDVENDOR_ACTIVATE,
        MSG_TALENT_WIPE_CONFIRM,
        SMSG_ACCOUNT_DATA_TIMES,
        SMSG_ACHIEVEMENT_DELETED,
        SMSG_ACHIEVEMENT_EARNED,
        SMSG_ACTION_BUTTONS,
        SMSG_ACTIVATETAXIREPLY,
        SMSG_ADDON_INFO,
        SMSG_ADD_RUNE_POWER,
        SMSG_AI_REACTION,
        SMSG_ALL_ACHIEVEMENT_DATA,
        SMSG_AREA_SPIRIT_HEALER_TIME,
        SMSG_AREA_TRIGGER_MESSAGE,
        SMSG_ARENA_ERROR,
        SMSG_ARENA_OPPONENT_UPDATE,
        SMSG_ARENA_TEAM_CHANGE_FAILED_QUEUED,
        SMSG_ARENA_TEAM_COMMAND_RESULT,
        SMSG_ARENA_TEAM_EVENT,
        SMSG_ARENA_TEAM_INVITE,
        SMSG_ARENA_TEAM_QUERY_RESPONSE,
        SMSG_ARENA_TEAM_ROSTER,
        SMSG_ARENA_TEAM_STATS,
        SMSG_ATTACKERSTATEUPDATE,
        SMSG_ATTACKSTART,
        SMSG_ATTACKSTOP,
        SMSG_ATTACKSWING_BADFACING,
        SMSG_ATTACKSWING_CANT_ATTACK,
        SMSG_ATTACKSWING_DEADTARGET,
        SMSG_ATTACKSWING_NOTINRANGE,
        SMSG_AUCTION_BIDDER_LIST_RESULT,
        SMSG_AUCTION_BIDDER_NOTIFICATION,
        SMSG_AUCTION_COMMAND_RESULT,
        SMSG_AUCTION_LIST_PENDING_SALES,
        SMSG_AUCTION_LIST_RESULT,
        SMSG_AUCTION_OWNER_LIST_RESULT,
        SMSG_AUCTION_OWNER_NOTIFICATION,
        SMSG_AUCTION_REMOVED_NOTIFICATION,
        SMSG_AURACASTLOG,
        SMSG_AURA_UPDATE,
        SMSG_AURA_UPDATE_ALL,
        SMSG_AUTH_CHALLENGE,
        SMSG_AUTH_RESPONSE,
        SMSG_AVAILABLE_VOICE_CHANNEL,
        SMSG_BARBER_SHOP_RESULT,
        SMSG_BATTLEFIELD_LIST,
        SMSG_BATTLEFIELD_MGR_EJECTED,
        SMSG_BATTLEFIELD_MGR_EJECT_PENDING,
        SMSG_BATTLEFIELD_MGR_ENTERED,
        SMSG_BATTLEFIELD_MGR_ENTRY_INVITE,
        SMSG_BATTLEFIELD_MGR_QUEUE_INVITE,
        SMSG_BATTLEFIELD_MGR_QUEUE_REQUEST_RESPONSE,
        SMSG_BATTLEFIELD_MGR_STATE_CHANGE,
        SMSG_BATTLEFIELD_PORT_DENIED,
        SMSG_BATTLEFIELD_STATUS1,
        SMSG_BATTLEFIELD_STATUS2,
        SMSG_BATTLEFIELD_STATUS3,
        SMSG_BATTLEFIELD_STATUS4,
        SMSG_BATTLEGROUND_INFO_THROTTLED,
        SMSG_BATTLEGROUND_PLAYER_JOINED,
        SMSG_BATTLEGROUND_PLAYER_LEFT,
        SMSG_BATTLEGROUND_PLAYER_POSITIONS,
        SMSG_BINDER_CONFIRM,
        SMSG_BINDPOINTUPDATE,
        SMSG_BINDZONEREPLY,
        SMSG_BREAK_TARGET,
        SMSG_BUY_BANK_SLOT_RESULT,
        SMSG_BUY_FAILED,
        SMSG_BUY_ITEM,
        SMSG_CALENDAR_ACTION_PENDING,
        SMSG_CALENDAR_ARENA_TEAM,
        SMSG_CALENDAR_COMMAND_RESULT,
        SMSG_CALENDAR_EVENT_INVITE,
        SMSG_CALENDAR_EVENT_INVITE_ALERT,
        SMSG_CALENDAR_EVENT_INVITE_REMOVED,
        SMSG_CALENDAR_EVENT_INVITE_REMOVED_ALERT,
        SMSG_CALENDAR_EVENT_INVITE_STATUS_ALERT,
        SMSG_CALENDAR_EVENT_MODERATOR_STATUS_ALERT,
        SMSG_CALENDAR_EVENT_REMOVED_ALERT,
        SMSG_CALENDAR_EVENT_STATUS,
        SMSG_CALENDAR_EVENT_UPDATED_ALERT,
        SMSG_CALENDAR_FILTER_GUILD,
        SMSG_CALENDAR_RAID_LOCKOUT_ADDED,
        SMSG_CALENDAR_RAID_LOCKOUT_REMOVED,
        SMSG_CALENDAR_SEND_CALENDAR,
        SMSG_CALENDAR_SEND_EVENT,
        SMSG_CALENDAR_SEND_NUM_PENDING,
        SMSG_CALENDAR_UPDATE_INVITE_LIST,
        SMSG_CALENDAR_UPDATE_INVITE_LIST2,
        SMSG_CALENDAR_UPDATE_INVITE_LIST3,
        SMSG_CAMERA_SHAKE,
        SMSG_CANCEL_AUTO_REPEAT,
        SMSG_CANCEL_COMBAT,
        SMSG_CAST_FAILED,
        SMSG_CHANNEL_LIST,
        SMSG_CHANNEL_MEMBER_COUNT,
        SMSG_CHANNEL_NOTIFY,
        SMSG_CHARACTER_LOGIN_FAILED,
        SMSG_CHARACTER_PROFILE,
        SMSG_CHARACTER_PROFILE_REALM_CONNECTED,
        SMSG_CHAR_CREATE,
        SMSG_CHAR_CUSTOMIZE,
        SMSG_CHAR_DELETE,
        SMSG_CHAR_ENUM,
        SMSG_CHAR_FACTION_CHANGE,
        SMSG_CHAR_RENAME,
        SMSG_CHAT_PLAYER_AMBIGUOUS,
        SMSG_CHAT_PLAYER_NOT_FOUND,
        SMSG_CHAT_RESTRICTED,
        SMSG_CHAT_WRONG_FACTION,
        SMSG_CHEAT_DUMP_ITEMS_DEBUG_ONLY_RESPONSE,
        SMSG_CHEAT_DUMP_ITEMS_DEBUG_ONLY_RESPONSE_WRITE_FILE,
        SMSG_CHEAT_PLAYER_LOOKUP,
        SMSG_CHECK_FOR_BOTS,
        SMSG_CLEAR_COOLDOWN,
        SMSG_CLEAR_EXTRA_AURA_INFO_OBSOLETE,
        SMSG_CLEAR_FAR_SIGHT_IMMEDIATE,
        SMSG_CLEAR_TARGET,
        SMSG_CLIENTCACHE_VERSION,
        SMSG_CLIENT_CONTROL_UPDATE,
        SMSG_COMBAT_LOG_MULTIPLE,
        SMSG_COMMENTATOR_GET_PLAYER_INFO,
        SMSG_COMMENTATOR_MAP_INFO,
        SMSG_COMMENTATOR_PLAYER_INFO,
        SMSG_COMMENTATOR_STATE_CHANGED,
        SMSG_COMPLAIN_RESULT,
        SMSG_COMPRESSED_MOVES,
        SMSG_COMPRESSED_UPDATE_OBJECT,
        SMSG_COMSAT_CONNECT_FAIL,
        SMSG_COMSAT_DISCONNECT,
        SMSG_COMSAT_RECONNECT_TRY,
        SMSG_CONTACT_LIST,
        SMSG_CONVERT_RUNE,
        SMSG_COOLDOWN_CHEAT,
        SMSG_COOLDOWN_EVENT,
        SMSG_CORPSE_MAP_POSITION_QUERY_RESPONSE,
        SMSG_CORPSE_NOT_IN_INSTANCE,
        SMSG_CORPSE_RECLAIM_DELAY,
        SMSG_CREATURE_QUERY_RESPONSE,
        SMSG_CRITERIA_DELETED,
        SMSG_CRITERIA_UPDATE,
        SMSG_CROSSED_INEBRIATION_THRESHOLD,
        SMSG_DAMAGE_CALC_LOG,
        SMSG_DAMAGE_DONE_OBSOLETE,
        SMSG_DANCE_QUERY_RESPONSE,
        SMSG_DEATH_RELEASE_LOC,
        SMSG_DEBUGAURAPROC,
        SMSG_DEBUG_LIST_TARGETS,
        SMSG_DEFENSE_MESSAGE,
        SMSG_DESTROY_OBJECT,
        SMSG_DESTRUCTIBLE_BUILDING_DAMAGE,
        SMSG_DISMOUNT,
        SMSG_DISMOUNTRESULT,
        SMSG_DISPEL_FAILED,
        SMSG_DUEL_COMPLETE,
        SMSG_DUEL_COUNTDOWN,
        SMSG_DUEL_INBOUNDS,
        SMSG_DUEL_OUTOFBOUNDS,
        SMSG_DUEL_REQUESTED,
        SMSG_DUEL_WINNER,
        SMSG_DUMP_OBJECTS_DATA,
        SMSG_DURABILITY_DAMAGE_DEATH,
        SMSG_DYNAMIC_DROP_ROLL_RESULT,
        SMSG_ECHO_PARTY_SQUELCH,
        SMSG_EMOTE,
        SMSG_ENABLE_BARBER_SHOP,
        SMSG_ENCHANTMENTLOG,
        SMSG_ENVIRONMENTALDAMAGELOG,
        SMSG_EQUIPMENT_SET_LIST,
        SMSG_EQUIPMENT_SET_SAVED,
        SMSG_EQUIPMENT_SET_USE_RESULT,
        SMSG_EXPECTED_SPAM_RECORDS,
        SMSG_EXPLORATION_EXPERIENCE,
        SMSG_FEATURE_SYSTEM_STATUS,
        SMSG_FEIGN_DEATH_RESISTED,
        SMSG_FISH_ESCAPED,
        SMSG_FISH_NOT_HOOKED,
        SMSG_FLIGHT_SPLINE_SYNC,
        SMSG_FORCEACTIONSHOW,
        SMSG_FORCED_DEATH_UPDATE,
        SMSG_FORCE_DISPLAY_UPDATE,
        SMSG_FORCE_FLIGHT_BACK_SPEED_CHANGE,
        SMSG_FORCE_FLIGHT_SPEED_CHANGE,
        SMSG_FORCE_MOVE_ROOT,
        SMSG_FORCE_MOVE_UNROOT,
        SMSG_FORCE_PITCH_RATE_CHANGE,
        SMSG_FORCE_RUN_BACK_SPEED_CHANGE,
        SMSG_FORCE_RUN_SPEED_CHANGE,
        SMSG_FORCE_SEND_QUEUED_PACKETS,
        SMSG_FORCE_SWIM_BACK_SPEED_CHANGE,
        SMSG_FORCE_SWIM_SPEED_CHANGE,
        SMSG_FORCE_TURN_RATE_CHANGE,
        SMSG_FORCE_UNK1_SPEED_CHANGE,
        SMSG_FORCE_UNK2_SPEED_CHANGE,
        SMSG_FORCE_WALK_SPEED_CHANGE,
        SMSG_FRIEND_STATUS,
        SMSG_GAMEOBJECT_CUSTOM_ANIM,
        SMSG_GAMEOBJECT_DESPAWN_ANIM,
        SMSG_GAMEOBJECT_PAGETEXT,
        SMSG_GAMEOBJECT_QUERY_RESPONSE,
        SMSG_GAMEOBJECT_RESET_STATE,
        SMSG_GAMESPEED_SET,
        SMSG_GAMETIMEBIAS_SET,
        SMSG_GAMETIME_SET,
        SMSG_GAMETIME_UPDATE,
        SMSG_GHOSTEE_GONE,
        SMSG_GMRESPONSE_DB_ERROR,
        SMSG_GMRESPONSE_RECEIVED,
        SMSG_GMRESPONSE_STATUS_UPDATE,
        SMSG_GMTICKET_CREATE,
        SMSG_GMTICKET_DELETETICKET,
        SMSG_GMTICKET_GETTICKET,
        SMSG_GMTICKET_SYSTEMSTATUS,
        SMSG_GMTICKET_UPDATETEXT,
        SMSG_GM_MESSAGECHAT,
        SMSG_GM_TICKET_STATUS_UPDATE,
        SMSG_GODMODE,
        SMSG_GOGOGO_OBSOLETE,
        SMSG_GOSSIP_COMPLETE,
        SMSG_GOSSIP_MESSAGE,
        SMSG_GOSSIP_POI,
        SMSG_GROUPACTION_THROTTLED,
        SMSG_GROUP_CANCEL,
        SMSG_GROUP_DECLINE,
        SMSG_GROUP_DESTROYED,
        SMSG_GROUP_INVITE,
        SMSG_GROUP_JOINED_BATTLEGROUND,
        SMSG_GROUP_LIST,
        SMSG_GROUP_SET_LEADER,
        SMSG_GROUP_UNINVITE,
        SMSG_GUILD_BANK_LIST,
        SMSG_GUILD_COMMAND_RESULT,
        SMSG_GUILD_DECLINE,
        SMSG_GUILD_EVENT,
        SMSG_GUILD_INFO,
        SMSG_GUILD_INVITE,
        SMSG_GUILD_MAX_DAILY_XP,
        SMSG_GUILD_NEWS_UPDATE,
        SMSG_GUILD_QUERY_RESPONSE,
        SMSG_GUILD_RANK,
        SMSG_GUILD_RANKS_UPDATE,
        SMSG_GUILD_REWARDS_LIST,
        SMSG_GUILD_ROSTER,
        SMSG_GUILD_TRADESKILL_UPDATE,
        SMSG_GUILD_UPDATE_ROSTER,
        SMSG_GUILD_XP_UPDATE,
        SMSG_HEALTH_UPDATE,
        SMSG_HIGHEST_THREAT_UPDATE,
        SMSG_IGNORE_DIMINISHING_RETURNS_CHEAT,
        SMSG_IGNORE_REQUIREMENTS_CHEAT,
        SMSG_INITIALIZE_FACTIONS,
        SMSG_INITIAL_SPELLS,
        SMSG_INIT_CURRENCY,
        SMSG_INIT_EXTRA_AURA_INFO_OBSOLETE,
        SMSG_INIT_WORLD_STATES,
        SMSG_INSPECT,
        SMSG_INSPECT_HONOR_STATS,
        SMSG_INSPECT_TALENT,
        SMSG_INSTANCE_DIFFICULTY,
        SMSG_INSTANCE_LOCK_WARNING_QUERY,
        SMSG_INSTANCE_RESET,
        SMSG_INSTANCE_RESET_FAILED,
        SMSG_INSTANCE_SAVE_CREATED,
        SMSG_INVALIDATE_DANCE,
        SMSG_INVALIDATE_PLAYER,
        SMSG_INVALID_PROMOTION_CODE,
        SMSG_INVENTORY_CHANGE_FAILURE,
        SMSG_ITEM_COOLDOWN,
        SMSG_ITEM_ENCHANT_TIME_UPDATE,
        SMSG_ITEM_NAME_QUERY_RESPONSE,
        SMSG_ITEM_PUSH_RESULT,
        SMSG_ITEM_QUERY_MULTIPLE_RESPONSE,
        SMSG_ITEM_QUERY_SINGLE_RESPONSE,
        SMSG_ITEM_REFUND_INFO_RESPONSE,
        SMSG_ITEM_REFUND_RESULT,
        SMSG_ITEM_TEXT_QUERY_RESPONSE,
        SMSG_ITEM_TIME_UPDATE,
        SMSG_JOINED_BATTLEGROUND_QUEUE,
        SMSG_KICK_REASON,
        SMSG_LEARNED_DANCE_MOVES,
        SMSG_LEARNED_SPELL,
        SMSG_LEVELUP_INFO,
        SMSG_LFG_BOOT_PROPOSAL_UPDATE,
        SMSG_LFG_DISABLED,
        SMSG_LFG_JOIN_RESULT,
        SMSG_LFG_OFFER_CONTINUE,
        SMSG_LFG_OPEN_FROM_GOSSIP,
        SMSG_LFG_PARTY_INFO,
        SMSG_LFG_PLAYER_INFO,
        SMSG_LFG_PLAYER_REWARD,
        SMSG_LFG_PROPOSAL_UPDATE,
        SMSG_LFG_QUEUE_STATUS,
        SMSG_LFG_ROLE_CHECK_UPDATE,
        SMSG_LFG_ROLE_CHOSEN,
        SMSG_LFG_TELEPORT_DENIED,
        SMSG_LFG_UPDATE_LIST,
        SMSG_LFG_UPDATE_PARTY,
        SMSG_LFG_UPDATE_PLAYER,
        SMSG_LIST_INVENTORY,
        SMSG_LOGIN_SETTIMESPEED,
        SMSG_LOGIN_VERIFY_WORLD,
        SMSG_LOGOUT_CANCEL_ACK,
        SMSG_LOGOUT_COMPLETE,
        SMSG_LOGOUT_RESPONSE,
        SMSG_LOG_XPGAIN,
        SMSG_LOOT_ALL_PASSED,
        SMSG_LOOT_CLEAR_MONEY,
        SMSG_LOOT_ITEM_NOTIFY,
        SMSG_LOOT_LIST,
        SMSG_LOOT_MASTER_LIST,
        SMSG_LOOT_MONEY_NOTIFY,
        SMSG_LOOT_RELEASE_RESPONSE,
        SMSG_LOOT_REMOVED,
        SMSG_LOOT_RESPONSE,
        SMSG_LOOT_ROLL,
        SMSG_LOOT_ROLL_WON,
        SMSG_LOOT_SLOT_CHANGED,
        SMSG_LOOT_START_ROLL,
        SMSG_LOTTERY_QUERY_RESULT_OBSOLETE,
        SMSG_LOTTERY_RESULT_OBSOLETE,
        SMSG_MAIL_LIST_RESULT,
        SMSG_MEETINGSTONE_COMPLETE,
        SMSG_MEETINGSTONE_IN_PROGRESS,
        SMSG_MEETINGSTONE_MEMBER_ADDED,
        SMSG_MEETINGSTONE_SETQUEUE,
        SMSG_MESSAGECHAT,
        SMSG_MINIGAME_MOVE_FAILED,
        SMSG_MINIGAME_SETUP,
        SMSG_MINIGAME_STATE,
        SMSG_MIRRORIMAGE_DATA,
        SMSG_MODIFY_COOLDOWN,
        SMSG_MONSTER_MOVE,
        SMSG_MONSTER_MOVE_TRANSPORT,
        SMSG_MOTD,
        SMSG_MOUNTRESULT,
        SMSG_MOUNTSPECIAL_ANIM,
        SMSG_MOVE_ABANDON_TRANSPORT,
        SMSG_MOVE_FEATHER_FALL,
        SMSG_MOVE_KNOCK_BACK,
        SMSG_MOVE_LAND_WALK,
        SMSG_MOVE_LEVITATING,
        SMSG_MOVE_NORMAL_FALL,
        SMSG_MOVE_SET_CAN_FLY,
        SMSG_MOVE_SET_FLIGHT,
        SMSG_MOVE_SET_HOVER,
        SMSG_MOVE_SET_WALK_IN_AIR,
        SMSG_MOVE_UNSET_CAN_FLY,
        SMSG_MOVE_UNSET_FLIGHT,
        SMSG_MOVE_UNSET_HOVER,
        SMSG_MOVE_UNSET_WALK_IN_AIR,
        SMSG_MOVE_WATER_WALK,
        SMSG_MULTIPLE_PACKETS,
        SMSG_NAME_QUERY_RESPONSE,
        SMSG_NEW_TAXI_PATH,
        SMSG_NEW_WORLD,
        SMSG_NOTIFICATION,
        SMSG_NOTIFY_DANCE,
        SMSG_NOTIFY_DEST_LOC_SPELL_CAST,
        SMSG_NPC_TEXT_UPDATE,
        SMSG_NPC_WONT_TALK,
        SMSG_OFFER_PETITION_ERROR,
        SMSG_ON_CANCEL_EXPECTED_RIDE_VEHICLE_AURA,
        SMSG_OPEN_CONTAINER,
        SMSG_OVERRIDE_LIGHT,
        SMSG_PAGE_TEXT_QUERY_RESPONSE,
        SMSG_PARTYKILLLOG,
        SMSG_PARTY_COMMAND_RESULT,
        SMSG_PARTY_MEMBER_STATS,
        SMSG_PARTY_MEMBER_STATS_FULL,
        SMSG_PAUSE_MIRROR_TIMER,
        SMSG_PERIODICAURALOG,
        SMSG_PETGODMODE,
        SMSG_PETITION_QUERY_RESPONSE,
        SMSG_PETITION_SHOWLIST,
        SMSG_PETITION_SHOW_SIGNATURES,
        SMSG_PETITION_SIGN_RESULTS,
        SMSG_PET_ACTION_FEEDBACK,
        SMSG_PET_ACTION_SOUND,
        SMSG_PET_BROKEN,
        SMSG_PET_CAST_FAILED,
        SMSG_PET_DISMISS_SOUND,
        SMSG_PET_GUIDS,
        SMSG_PET_LEARNED_SPELL,
        SMSG_PET_MODE,
        SMSG_PET_NAME_INVALID,
        SMSG_PET_NAME_QUERY_RESPONSE,
        SMSG_PET_REMOVED_SPELL,
        SMSG_PET_RENAMEABLE,
        SMSG_PET_SPELLS,
        SMSG_PET_TAME_FAILURE,
        SMSG_PET_UNLEARN_CONFIRM,
        SMSG_PET_UPDATE_COMBO_POINTS,
        SMSG_PLAYED_TIME,
        SMSG_PLAYERBINDERROR,
        SMSG_PLAYERBOUND,
        SMSG_PLAYER_DIFFICULTY_CHANGE,
        SMSG_PLAYER_MOVE,
        SMSG_PLAYER_SKINNED,
        SMSG_PLAYER_VEHICLE_DATA,
        SMSG_PLAY_DANCE,
        SMSG_PLAY_MUSIC,
        SMSG_PLAY_OBJECT_SOUND,
        SMSG_PLAY_SOUND,
        SMSG_PLAY_SPELL_IMPACT,
        SMSG_PLAY_SPELL_VISUAL,
        SMSG_PLAY_TIME_WARNING,
        SMSG_PONG,
        SMSG_POWER_UPDATE,
        SMSG_PRE_RESURRECT,
        SMSG_PROCRESIST,
        SMSG_PROPOSE_LEVEL_GRANT,
        SMSG_PUREMOUNT_CANCELLED_OBSOLETE,
        SMSG_PVP_CREDIT,
        SMSG_PVP_TYPES_ENABLED,
        SMSG_QUERY_QUESTS_COMPLETED_RESPONSE,
        SMSG_QUERY_TIME_RESPONSE,
        SMSG_QUESTGIVER_OFFER_REWARD,
        SMSG_QUESTGIVER_QUEST_COMPLETE,
        SMSG_QUESTGIVER_QUEST_DETAILS,
        SMSG_QUESTGIVER_QUEST_FAILED,
        SMSG_QUESTGIVER_QUEST_INVALID,
        SMSG_QUESTGIVER_QUEST_LIST,
        SMSG_QUESTGIVER_REQUEST_ITEMS,
        SMSG_QUESTGIVER_STATUS,
        SMSG_QUESTGIVER_STATUS_MULTIPLE,
        SMSG_QUESTLOG_FULL,
        SMSG_QUESTUPDATE_ADD_ITEM,
        SMSG_QUESTUPDATE_ADD_KILL,
        SMSG_QUESTUPDATE_ADD_PVP_KILL,
        SMSG_QUESTUPDATE_COMPLETE,
        SMSG_QUESTUPDATE_FAILED,
        SMSG_QUESTUPDATE_FAILEDTIMER,
        SMSG_QUEST_CONFIRM_ACCEPT,
        SMSG_QUEST_FORCE_REMOVED,
        SMSG_QUEST_POI_QUERY_RESPONSE,
        SMSG_QUEST_QUERY_RESPONSE,
        SMSG_RAID_GROUP_ONLY,
        SMSG_RAID_INSTANCE_INFO,
        SMSG_RAID_INSTANCE_MESSAGE,
        SMSG_RAID_READY_CHECK_ERROR,
        SMSG_READ_ITEM_FAILED,
        SMSG_READ_ITEM_OK,
        SMSG_REALM_SPLIT,
        SMSG_REAL_GROUP_UPDATE,
        SMSG_RECEIVED_MAIL,
        SMSG_REDIRECT_CLIENT,
        SMSG_REFER_A_FRIEND_FAILURE,
        SMSG_REMOVED_SPELL,
        SMSG_REPORT_PVP_AFK_RESULT,
        SMSG_RESET_FAILED_NOTIFY,
        SMSG_RESISTLOG,
        SMSG_RESPOND_INSPECT_ACHIEVEMENTS,
        SMSG_RESURRECT_FAILED,
        SMSG_RESURRECT_REQUEST,
        SMSG_RESYNC_RUNES,
        SMSG_RWHOIS,
        SMSG_SCRIPT_MESSAGE,
        SMSG_SELL_ITEM,
        SMSG_SEND_MAIL_RESULT,
        SMSG_SEND_QUEUED_PACKETS,
        SMSG_SEND_UNLEARN_SPELLS,
        SMSG_SERVERTIME,
        SMSG_SERVER_BUCK_DATA,
        SMSG_SERVER_BUCK_DATA_START,
        SMSG_SERVER_FIRST_ACHIEVEMENT,
        SMSG_SERVER_INFO_RESPONSE,
        SMSG_SERVER_MESSAGE,
        SMSG_SET_EXTRA_AURA_INFO_NEED_UPDATE_OBSOLETE,
        SMSG_SET_EXTRA_AURA_INFO_OBSOLETE,
        SMSG_SET_FACTION_ATWAR,
        SMSG_SET_FACTION_STANDING,
        SMSG_SET_FACTION_VISIBLE,
        SMSG_SET_FLAT_SPELL_MODIFIER,
        SMSG_SET_FORCED_REACTIONS,
        SMSG_SET_PCT_SPELL_MODIFIER,
        SMSG_SET_PHASE_SHIFT,
        SMSG_SET_PLAYER_DECLINED_NAMES_RESULT,
        SMSG_SET_PROFICIENCY,
        SMSG_SET_PROJECTILE_POSITION,
        SMSG_SHOWTAXINODES,
        SMSG_SHOW_BANK,
        SMSG_SPELLBREAKLOG,
        SMSG_SPELLDAMAGESHIELD,
        SMSG_SPELLDISPELLOG,
        SMSG_SPELLENERGIZELOG,
        SMSG_SPELLHEALLOG,
        SMSG_SPELLINSTAKILLLOG,
        SMSG_SPELLLOGEXECUTE,
        SMSG_SPELLLOGMISS,
        SMSG_SPELLNONMELEEDAMAGELOG,
        SMSG_SPELLORDAMAGE_IMMUNE,
        SMSG_SPELLSTEALLOG,
        SMSG_SPELL_CHANCE_PROC_LOG,
        SMSG_SPELL_CHANCE_RESIST_PUSHBACK,
        SMSG_SPELL_COOLDOWN,
        SMSG_SPELL_DELAYED,
        SMSG_SPELL_FAILED_OTHER,
        SMSG_SPELL_FAILURE,
        SMSG_SPELL_GO,
        SMSG_SPELL_START,
        SMSG_SPELL_UPDATE_CHAIN_TARGETS,
        SMSG_SPIRIT_HEALER_CONFIRM,
        SMSG_SPLINE_MOVE_FEATHER_FALL,
        SMSG_SPLINE_MOVE_LAND_WALK,
        SMSG_SPLINE_MOVE_NORMAL_FALL,
        SMSG_SPLINE_MOVE_ROOT,
        SMSG_SPLINE_MOVE_SET_FLYING,
        SMSG_SPLINE_MOVE_SET_HOVER,
        SMSG_SPLINE_MOVE_SET_RUN_MODE,
        SMSG_SPLINE_MOVE_SET_WALK_MODE,
        SMSG_SPLINE_MOVE_START_SWIM,
        SMSG_SPLINE_MOVE_STOP_SWIM,
        SMSG_SPLINE_MOVE_UNKNOWN_1235,
        SMSG_SPLINE_MOVE_UNKNOWN_1236,
        SMSG_SPLINE_MOVE_UNROOT,
        SMSG_SPLINE_MOVE_UNSET_FLYING,
        SMSG_SPLINE_MOVE_UNSET_HOVER,
        SMSG_SPLINE_MOVE_WATER_WALK,
        SMSG_SPLINE_SET_FLIGHT_BACK_SPEED,
        SMSG_SPLINE_SET_FLIGHT_SPEED,
        SMSG_SPLINE_SET_PITCH_RATE,
        SMSG_SPLINE_SET_RUN_BACK_SPEED,
        SMSG_SPLINE_SET_RUN_SPEED,
        SMSG_SPLINE_SET_SWIM_BACK_SPEED,
        SMSG_SPLINE_SET_SWIM_SPEED,
        SMSG_SPLINE_SET_TURN_RATE,
        SMSG_SPLINE_SET_WALK_SPEED,
        SMSG_STABLE_RESULT,
        SMSG_STANDSTATE_CHANGE_FAILURE_OBSOLETE,
        SMSG_STANDSTATE_UPDATE,
        SMSG_START_MIRROR_TIMER,
        SMSG_STOP_DANCE,
        SMSG_STOP_MIRROR_TIMER,
        SMSG_SUMMON_CANCEL,
        SMSG_SUMMON_REQUEST,
        SMSG_SUPERCEDED_SPELL,
        SMSG_TALENTS_INFO,
        SMSG_TALENTS_INVOLUNTARILY_RESET,
        SMSG_TAXINODE_STATUS,
        SMSG_TEXT_EMOTE,
        SMSG_THREAT_CLEAR,
        SMSG_THREAT_REMOVE,
        SMSG_THREAT_UPDATE,
        SMSG_TIME_SYNC_REQ,
        SMSG_TITLE_EARNED,
        SMSG_TOGGLE_XP_GAIN,
        SMSG_TOTEM_CREATED,
        SMSG_TRADE_STATUS,
        SMSG_TRADE_STATUS_EXTENDED,
        SMSG_TRAINER_BUY_RESULT,
        SMSG_TRAINER_LIST,
        SMSG_TRANSFER_ABORTED,
        SMSG_TRANSFER_PENDING,
        SMSG_TRIGGER_CINEMATIC,
        SMSG_TRIGGER_MOVIE,
        SMSG_TURN_IN_PETITION_RESULTS,
        SMSG_TUTORIAL_FLAGS,
        SMSG_UNIT_SPELLCAST_START,
        SMSG_UNKNOWN_1240,
        SMSG_UNKNOWN_1276,
        SMSG_UNKNOWN_1295,
        SMSG_UNKNOWN_1302,
        SMSG_UNKNOWN_1304,
        SMSG_UNKNOWN_1308,
        SMSG_UNKNOWN_1310,
        SMSG_UNKNOWN_1311,
        SMSG_UNKNOWN_1312,
        SMSG_UNKNOWN_1314,
        SMSG_UNKNOWN_1315,
        SMSG_UNKNOWN_1316,
        SMSG_UNKNOWN_1317,
        SMSG_UNKNOWN_1329,
        SMSG_UPDATE_ACCOUNT_DATA,
        SMSG_UPDATE_ACCOUNT_DATA_COMPLETE,
        SMSG_UPDATE_COMBO_POINTS,
        SMSG_UPDATE_CURRENCY,
        SMSG_UPDATE_CURRENCY_WEEK_LIMIT,
        SMSG_UPDATE_INSTANCE_ENCOUNTER_UNIT,
        SMSG_UPDATE_INSTANCE_OWNERSHIP,
        SMSG_UPDATE_ITEM_ENCHANTMENTS,
        SMSG_UPDATE_LAST_INSTANCE,
        SMSG_UPDATE_LFG_LIST,
        SMSG_UPDATE_OBJECT,
        SMSG_UPDATE_WORLD_STATE,
        SMSG_USERLIST_ADD,
        SMSG_USERLIST_REMOVE,
        SMSG_USERLIST_UPDATE,
        SMSG_VOICESESSION_FULL,
        SMSG_VOICE_CHAT_STATUS,
        SMSG_VOICE_PARENTAL_CONTROLS,
        SMSG_VOICE_SESSION_ADJUST_PRIORITY,
        SMSG_VOICE_SESSION_ENABLE,
        SMSG_VOICE_SESSION_LEAVE,
        SMSG_VOICE_SESSION_ROSTER_UPDATE,
        SMSG_VOICE_SET_TALKER_MUTED,
        SMSG_WARDEN_DATA,
        SMSG_WEATHER,
        SMSG_WHO,
        SMSG_WHOIS,
        SMSG_WORLD_STATE_UI_TIMER_UPDATE,
        SMSG_ZONE_UNDER_ATTACK


        /* Uncomment this and comment out values above if you don't want to use the OpcodeDB feature
        CMSG_ACCEPT_LEVEL_GRANT                          = 0x0E2A2, // 14333
        CMSG_ACCEPT_TRADE                                = 0x008C0, // 14333
        CMSG_ACTIVATETAXI                                = 0x0A2AF, // 14333
        CMSG_ACTIVATETAXIEXPRESS                         = 0x0E6E6, // 14333
        CMSG_ADD_FRIEND                                  = 0x02AA3, // 14333
        CMSG_ADD_IGNORE                                  = 0x06E66, // 14333
        CMSG_ADD_VOICE_IGNORE                            = 0x02AAE, // 14333
        CMSG_ALTER_APPEARANCE                            = 0x07EA3, // 14333
        CMSG_AREATRIGGER                                 = 0x062A6, // 14333
        CMSG_AREA_SPIRIT_HEALER_QUERY                    = 0x032EB, // 14333
        CMSG_AREA_SPIRIT_HEALER_QUEUE                    = 0x03AE6, // 14333
        CMSG_ARENA_TEAM_ACCEPT                           = 0x02EB7, // 14333
        CMSG_ARENA_TEAM_DECLINE                          = 0x0AEE7, // 14333
        CMSG_ARENA_TEAM_DISBAND                          = 0x0E2E3, // 14333
        CMSG_ARENA_TEAM_INVITE                           = 0x0AA3B, // 14333
        CMSG_ARENA_TEAM_LEADER                           = 0x06E6B, // 14333
        CMSG_ARENA_TEAM_LEAVE                            = 0x03A66, // 14333
        CMSG_ARENA_TEAM_REMOVE                           = 0x0BEEF, // 14333
        CMSG_ARENA_TEAM_ROSTER                           = 0x07A66, // 14333
        CMSG_ATTACKSTOP                                  = 0x06EAB, // 14333
        CMSG_ATTACKSWING                                 = 0x0663B, // 14333
        CMSG_AUCTION_LIST_BIDDER_ITEMS                   = 0x0BAF6, // 14333
        CMSG_AUCTION_LIST_ITEMS                          = 0x06E77, // 14333
        CMSG_AUCTION_LIST_OWNER_ITEMS                    = 0x02AAB, // 14333
        CMSG_AUCTION_PLACE_BID                           = 0x0227B, // 14333
        CMSG_AUCTION_REMOVE_ITEM                         = 0x0B62A, // 14333
        CMSG_AUCTION_SELL_ITEM                           = 0x06A6B, // 14333
        CMSG_AUTH_SESSION                                = 0x029A0, // 14333
        CMSG_AUTOEQUIP_ITEM                              = 0x0B2F6, // 14333
        CMSG_AUTOEQUIP_ITEM_SLOT                         = 0x0BE72, // 14333
        CMSG_AUTOSTORE_BAG_ITEM                          = 0x07E6A, // 14333
        CMSG_AUTOSTORE_LOOT_ITEM                         = 0x0FE7F, // 14333
        CMSG_BATTLEFIELD_JOIN                            = 0x0A860, // 14333
        CMSG_BATTLEFIELD_REQUEST_SCORE_DATA              = 0x0886B, // 14333
        CMSG_BATTLEFIELD_STATUS                          = 0x03620, // 14333
        CMSG_BATTLEGROUND_PLAYER_POSITIONS               = 0x098EB, // 14333
        CMSG_BATTLEMASTER_JOIN_ARENA                     = 0x0086A, // 14333
        CMSG_BINDER_ACTIVATE                             = 0x0EA6F, // 14333
        CMSG_BUG                                         = 0x06262, // 14333
        CMSG_BUYBACK_ITEM                                = 0x0AAAF, // 14333
        CMSG_BUY_BANK_SLOT                               = 0x0A2B6, // 14333
        CMSG_BUY_ITEM                                    = 0x0626A, // 14333
        CMSG_CALENDAR_ADD_EVENT                          = 0x0EAA2, // 14333
        CMSG_CALENDAR_ARENA_TEAM                         = 0x0BA7F, // 14333
        CMSG_CALENDAR_CONTEXT_EVENT_SIGNUP               = 0x0762B, // 14333
        CMSG_CALENDAR_COPY_EVENT                         = 0x0AEB6, // 14333
        CMSG_CALENDAR_EVENT_INVITE                       = 0x0EEB2, // 14333
        CMSG_CALENDAR_EVENT_MODERATOR_STATUS             = 0x06E37, // 14333
        CMSG_CALENDAR_EVENT_REMOVE_INVITE                = 0x0AA7A, // 14333
        CMSG_CALENDAR_EVENT_STATUS                       = 0x0A26F, // 14333
        CMSG_CALENDAR_GET_EVENT                          = 0x0FE6E, // 14333
        CMSG_CALENDAR_GET_NUM_PENDING                    = 0x02AEF, // 14333
        CMSG_CALENDAR_GUILD_FILTER                       = 0x03E72, // 14333
        CMSG_CALENDAR_REMOVE_EVENT                       = 0x0E6E7, // 14333
        CMSG_CALENDAR_UPDATE_EVENT                       = 0x0723A, // 14333
        CMSG_CANCEL_AURA                                 = 0x0BEEA, // 14333
        CMSG_CANCEL_AUTO_REPEAT_SPELL                    = 0x03662, // 14333
        CMSG_CANCEL_CAST                                 = 0x032F3, // 14333
        CMSG_CANCEL_CHANNELLING                          = 0x0AA63, // 14333
        CMSG_CANCEL_GROWTH_AURA                          = 0x03E7E, // 14333
        CMSG_CANCEL_MOUNT_AURA                           = 0x0FEBA, // 14333
        CMSG_CANCEL_TEMP_ENCHANTMENT                     = 0x0A22E, // 14333
        CMSG_CANCEL_TRADE                                = 0x028EA, // 14333
        CMSG_CAST_SPELL                                  = 0x072FB, // 14333
        CMSG_CHANNEL_LIST                                = 0x07AA6, // 14333
        CMSG_CHAR_CREATE                                 = 0x02A22, // 14333
        CMSG_CHAR_CUSTOMIZE                              = 0x02A66, // 14333
        CMSG_CHAR_DELETE                                 = 0x06E32, // 14333
        CMSG_CHAR_ENUM                                   = 0x01091, // 14333
        CMSG_CHAR_FACTION_CHANGE                         = 0x07636, // 14333
        CMSG_CHAR_RACE_CHANGE                            = 0x0B276, // 14333
        CMSG_CHAR_RENAME                                 = 0x06263, // 14333
        CMSG_CLEAR_CHANNEL_WATCH                         = 0x03EA2, // 14333
        CMSG_CLEAR_TRADE_ITEM                            = 0x009A0, // 14333
        CMSG_COMMENTATOR_ENABLE                          = 0x0366F, // 14333
        CMSG_COMMENTATOR_ENTER_INSTANCE                  = 0x0362F, // 14333
        CMSG_COMMENTATOR_GET_MAP_INFO                    = 0x0E2F2, // 14333
        CMSG_COMMENTATOR_GET_PLAYER_INFO                 = 0x0BA7B, // 14333
        CMSG_COMMENTATOR_INSTANCE_COMMAND                = 0x072F7, // 14333
        CMSG_COMMENTATOR_SKIRMISH_QUEUE_COMMAND          = 0x07A76, // 14333
        CMSG_COMPLAIN                                    = 0x0EA63, // 14333
        CMSG_COMPLETE_CINEMATIC                          = 0x0B2F7, // 14333
        CMSG_COMPLETE_MOVIE                              = 0x0F63F, // 14333
        CMSG_CORPSE_MAP_POSITION_QUERY                   = 0x0E626, // 14333
        CMSG_DEL_FRIEND                                  = 0x03E3B, // 14333
        CMSG_DEL_IGNORE                                  = 0x07AB6, // 14333
        CMSG_DESTROYITEM                                 = 0x06E7A, // 14333
        CMSG_DESTROY_ITEMS                               = 0x06E7A, // 14333
        CMSG_DUEL_ACCEPTED                               = 0x0F63B, // 14333
        CMSG_EJECT_PASSENGER                             = 0x03E6E, // 14333
        CMSG_EQUIPMENT_SET_DELETE                        = 0x0FEBF, // 14333
        CMSG_EQUIPMENT_SET_SAVE                          = 0x0E26E, // 14333
        CMSG_GAMEOBJ_REPORT_USE                          = 0x0EE27, // 14333
        CMSG_GAMEOBJ_USE                                 = 0x072BB, // 14333
        CMSG_GAMETIME_SET                                = 0x0F2AB, // 14333
        CMSG_GET_MAIL_LIST                               = 0x0EA33, // 14333
        CMSG_GET_MIRRORIMAGE_DATA                        = 0x0EEEA, // 14333
        CMSG_GMRESPONSE_RESOLVE                          = 0x0363E, // 14333
        CMSG_GMSURVEY_SUBMIT                             = 0x0BEBB, // 14333
        CMSG_GMTICKET_CREATE                             = 0x02223, // 14333
        CMSG_GMTICKET_DELETETICKET                       = 0x0FE22, // 14333
        CMSG_GMTICKET_GETTICKET                          = 0x032A2, // 14333
        CMSG_GMTICKET_SYSTEMSTATUS                       = 0x07E67, // 14333
        CMSG_GMTICKET_UPDATETEXT                         = 0x06A2B, // 14333
        CMSG_GM_REPORT_LAG                               = 0x0E2A6, // 14333
        CMSG_GOSSIP_HELLO                                = 0x0EE7B, // 14333
        CMSG_GOSSIP_SELECT_OPTION                        = 0x02AE3, // 14333
        CMSG_GRANT_LEVEL                                 = 0x03A2E, // 14333
        CMSG_GROUP_ASSISTANT_LEADER                      = 0x06223, // 14333
        CMSG_GROUP_CHANGE_SUB_GROUP                      = 0x026A2, // 14333
        CMSG_GROUP_DISBAND                               = 0x02AEB, // 14333
        CMSG_GROUP_INVITE                                = 0x04051, // 14333
        CMSG_GROUP_RAID_CONVERT                          = 0x036BE, // 14333
        CMSG_GROUP_SET_LEADER                            = 0x0B27A, // 14333
        CMSG_GROUP_SWAP_SUB_GROUP                        = 0x0E222, // 14333
        CMSG_GROUP_UNINVITE_GUID                         = 0x0FEBB, // 14333
        CMSG_GUILD_BANKER_ACTIVATE                       = 0x026B2, // 14333
        CMSG_GUILD_BANK_BUY_TAB                          = 0x036B3, // 14333
        CMSG_GUILD_BANK_DEPOSIT_MONEY                    = 0x02A2F, // 14333
        CMSG_GUILD_BANK_NOTE                             = 0x06E26, // 14333
        CMSG_GUILD_BANK_QUERY_TAB                        = 0x0A623, // 14333
        CMSG_GUILD_BANK_SWAP_ITEMS                       = 0x0FAF2, // 14333
        CMSG_GUILD_BANK_UPDATE_TAB                       = 0x0727B, // 14333
        CMSG_GUILD_BANK_WITHDRAW_MONEY                   = 0x022EE, // 14333
        CMSG_GUILD_INFO                                  = 0x0226E, // 14333
        CMSG_GUILD_INVITE                                = 0x0F232, // 14333
        CMSG_HEARTH_AND_RESURRECT                        = 0x07E66, // 14333
        CMSG_INSPECT                                     = 0x06AAF, // 14333
        CMSG_ITEM_REFUND                                 = 0x0762A, // 14333
        CMSG_ITEM_REFUND_INFO                            = 0x0E276, // 14333
        CMSG_ITEM_TEXT_QUERY                             = 0x07EF7, // 14333
        CMSG_JOIN_CHANNEL                                = 0x05B15, // 14333
        CMSG_KEEP_ALIVE                                  = 0x0E6BF, // 14333
        CMSG_LEARN_PREVIEW_TALENTS_PET                   = 0x032FA, // 14333
        CMSG_LEAVE_BATTLEFIELD                           = 0x06EF2, // 14333
        CMSG_LEAVE_CHANNEL                               = 0x05395, // 14333
        CMSG_LFD_PARTY_LOCK_INFO_REQUEST                 = 0x0B2FE, // 14333
        CMSG_LFG_JOIN                                    = 0x03EB2, // 14333
        CMSG_LFG_LEAVE                                   = 0x072A6, // 14333
        CMSG_LFG_PROPOSAL_RESULT                         = 0x0BAEA, // 14333
        CMSG_LFG_SET_BOOT_VOTE                           = 0x0A6FB, // 14333
        CMSG_LFG_SET_ROLES                               = 0x026F7, // 14333
        CMSG_LFG_TELEPORT                                = 0x0B673, // 14333
        CMSG_LIST_INVENTORY                              = 0x0EAFB, // 14333
        CMSG_LOGOUT_CANCEL                               = 0x0F2BF, // 14333
        CMSG_LOGOUT_REQUEST                              = 0x0B2A6, // 14333
        CMSG_LOOT                                        = 0x0726B, // 14333
        CMSG_LOOT_METHOD                                 = 0x0EE62, // 14333
        CMSG_LOOT_MONEY                                  = 0x03AEA, // 14333
        CMSG_LOOT_RELEASE                                = 0x0E273, // 14333
        CMSG_LOOT_ROLL                                   = 0x02EAF, // 14333
        CMSG_MAIL_CREATE_TEXT_ITEM                       = 0x06A6F, // 14333
        CMSG_MAIL_MARK_AS_READ                           = 0x0A2AB, // 14333
        CMSG_MAIL_RETURN_TO_SENDER                       = 0x07662, // 14333
        CMSG_MAIL_TAKE_ITEM                              = 0x0FA3A, // 14333
        CMSG_MAIL_TAKE_MONEY                             = 0x0AAF2, // 14333
        CMSG_MEETINGSTONE_INFO                           = 0x07622, // 14333
        CMSG_MESSAGECHAT_AFK                             = 0x01191, // 14333
        CMSG_MESSAGECHAT_CHANNEL                         = 0x05BB5, // 14333
        CMSG_MESSAGECHAT_DND                             = 0x01B31, // 14333
        CMSG_MESSAGECHAT_EMOTE                           = 0x07EB6, // 14333
        CMSG_MESSAGECHAT_GUILD                           = 0x01111, // 14333
        CMSG_MESSAGECHAT_SAY                             = 0x059B5, // 14333
        CMSG_MESSAGECHAT_WHISPER                         = 0x05B35, // 14333
        CMSG_MESSAGECHAT_YELL                            = 0x013B1, // 14333
        CMSG_MINIGAME_MOVE                               = 0x0FAEA, // 14333
        CMSG_MOUNTSPECIAL_ANIM                           = 0x0AA6F, // 14333
        CMSG_NEXT_CINEMATIC_CAMERA                       = 0x0A2BA, // 14333
        CMSG_OFFER_PETITION                              = 0x02EFE, // 14333
        CMSG_OPEN_ITEM                                   = 0x03677, // 14333
        CMSG_OPT_OUT_OF_LOOT                             = 0x0BEA3, // 14333
        CMSG_PETITION_BUY                                = 0x02A26, // 14333
        CMSG_PETITION_SHOW_SIGNATURES                    = 0x0FA36, // 14333
        CMSG_PETITION_SIGN                               = 0x026BE, // 14333
        CMSG_PET_ACTION                                  = 0x07232, // 14333
        CMSG_PET_CANCEL_AURA                             = 0x066F6, // 14333
        CMSG_PET_LEARN_TALENT                            = 0x0F2E2, // 14333
        CMSG_PET_RENAME                                  = 0x0BAEE, // 14333
        CMSG_PET_SET_ACTION                              = 0x02A6E, // 14333
        CMSG_PET_SPELL_AUTOCAST                          = 0x066FE, // 14333
        CMSG_PET_STOP_ATTACK                             = 0x0FA66, // 14333
        CMSG_PING                                        = 0x02920, // 14333
        CMSG_PLAYED_TIME                                 = 0x0EEE2, // 14333
        CMSG_PLAYER_LOGIN                                = 0x010D1, // 14333
        CMSG_PLAYER_LOGOUT                               = 0x0EAEE, // 14333
        CMSG_PLAYER_VEHICLE_ENTER                        = 0x0EEA2, // 14333
        CMSG_PLAY_DANCE                                  = 0x0323B, // 14333
        CMSG_PUSHQUESTTOPARTY                            = 0x022B2, // 14333
        CMSG_QUERY_QUESTS_COMPLETED                      = 0x0FE33, // 14333
        CMSG_QUESTGIVER_ACCEPT_QUEST                     = 0x0F2AB, // 14333
        CMSG_QUESTGIVER_CANCEL                           = 0x0E263, // 14333
        CMSG_QUESTGIVER_CHOOSE_REWARD                    = 0x03EAB, // 14333
        CMSG_QUESTGIVER_COMPLETE_QUEST                   = 0x072E3, // 14333
        CMSG_QUESTGIVER_QUERY_QUEST                      = 0x0BEEB, // 14333
        CMSG_QUESTGIVER_REQUEST_REWARD                   = 0x0E27F, // 14333
        CMSG_QUESTGIVER_STATUS_MULTIPLE_QUERY            = 0x0A2FA, // 14333
        CMSG_QUESTGIVER_STATUS_QUERY                     = 0x07223, // 14333
        CMSG_QUESTLOG_REMOVE_QUEST                       = 0x03A3F, // 14333
        CMSG_QUEST_POI_QUERY                             = 0x0F2EE, // 14333
        CMSG_READY_FOR_ACCOUNT_DATA_TIMES                = 0x0F226, // 14333
        CMSG_READ_ITEM                                   = 0x06A67, // 14333
        CMSG_REALM_SPLIT                                 = 0x0B6E2, // 14333
        CMSG_RECLAIM_CORPSE                              = 0x07E76, // 14333
        CMSG_REDIRECTION_AUTH_PROOF                      = 0x02120, // 14333
        CMSG_REPAIR_ITEM                                 = 0x032BF, // 14333
        CMSG_REPOP_REQUEST                               = 0x0F23A, // 14333
        CMSG_REPORT_PVP_AFK                              = 0x06E22, // 14333
        CMSG_REQUEST_ACCOUNT_DATA                        = 0x07E3B, // 14333
        CMSG_REQUEST_PARTY_MEMBER_STATS                  = 0x0266B, // 14333
        CMSG_REQUEST_PET_INFO                            = 0x0A6A2, // 14333
        CMSG_REQUEST_PLAYER_VEHICLE_EXIT                 = 0x03A3E, // 14333
        CMSG_REQUEST_RATED_BG_INFO                       = 0x04000, // 14333
        CMSG_REQUEST_VEHICLE_NEXT_SEAT                   = 0x0EE72, // 14333
        CMSG_REQUEST_VEHICLE_PREV_SEAT                   = 0x0723F, // 14333
        CMSG_REQUEST_VEHICLE_SWITCH_SEAT                 = 0x02EBF, // 14333
        CMSG_RESET_INSTANCES                             = 0x0E22B, // 14333
        CMSG_RESURRECT_RESPONSE                          = 0x0BA32, // 14333
        CMSG_RETURN_TO_GRAVEYARD                         = 0x0B8EB, // 14333
        CMSG_SEARCH_LFG_JOIN                             = 0x0AA26, // 14333
        CMSG_SEARCH_LFG_LEAVE                            = 0x0FAEA, // 14333
        CMSG_SELF_RES                                    = 0x0B2B3, // 14333
        CMSG_SELL_ITEM                                   = 0x026B3, // 14333
        CMSG_SET_ACTIONBAR_TOGGLES                       = 0x0BE62, // 14333
        CMSG_SET_ACTION_BUTTON                           = 0x07AB3, // 14333
        CMSG_SET_ACTIVE_VOICE_CHANNEL                    = 0x02636, // 14333
        CMSG_SET_ALLOW_LOW_LEVEL_RAID1                   = 0x07EF3, // 14333
        CMSG_SET_CHANNEL_WATCH                           = 0x07AA6, // 14333
        CMSG_SET_CONTACT_NOTES                           = 0x0B2AA, // 14333
        CMSG_SET_GUILD_BANK_TEXT                         = 0x06E26, // 14333
        CMSG_SET_LFG_COMMENT                             = 0x0E676, // 14333
        CMSG_SET_PLAYER_DECLINED_NAMES                   = 0x03EE6, // 14333
        CMSG_SET_PRIMARY_TALENT_TREE                     = 0x0B627, // 14333
        CMSG_SET_SAVED_INSTANCE_EXTEND                   = 0x0AEAB, // 14333
        CMSG_SET_SELECTION                               = 0x06626, // 14333
        CMSG_SET_TITLE                                   = 0x0627B, // 14333
        CMSG_SET_TRADE_ITEM                              = 0x09863, // 14333
        CMSG_SOCKET_GEMS                                 = 0x026AB, // 14333
        CMSG_SPIRIT_HEALER_ACTIVATE                      = 0x0B6B6, // 14333
        CMSG_SPLIT_ITEM                                  = 0x06E67, // 14333
        CMSG_STANDSTATECHANGE                            = 0x032EA, // 14333
        CMSG_START_QUEST                                 = 0x098C8, // 14333
        CMSG_STOP_DANCE                                  = 0x02EF3, // 14333
        CMSG_SUMMON_RESPONSE                             = 0x07A3A, // 14333
        CMSG_SWAP_ITEM                                   = 0x03ABB, // 14333
        CMSG_TAXINODE_STATUS_QUERY                       = 0x06622, // 14333
        CMSG_TOGGLE_PVP                                  = 0x0BA6F, // 14333
        CMSG_TOTEM_DESTROYED                             = 0x03EB7, // 14333
        CMSG_TRAINER_BUY_SPELL                           = 0x0BA27, // 14333
        CMSG_TRAINER_LIST                                = 0x0BEBA, // 14333
        CMSG_TURN_IN_PETITION                            = 0x0727A, // 14333
        CMSG_TUTORIAL_CLEAR                              = 0x0B2FB, // 14333
        CMSG_TUTORIAL_FLAG                               = 0x0266A, // 14333
        CMSG_TUTORIAL_RESET                              = 0x0B6BF, // 14333
        CMSG_UNACCEPT_TRADE                              = 0x08848, // 14333
        CMSG_UNKNOWN_1296                                = 0x009A0, // 14333
        CMSG_UNLEARN_SKILL                               = 0x0B2EE, // 14333
        CMSG_UPDATE_ACCOUNT_DATA                         = 0x066FF, // 14333
        CMSG_USE_ITEM                                    = 0x022B3, // 14333
        CMSG_VOICE_SESSION_ENABLE                        = 0x0BAA3, // 14333
        CMSG_WARDEN_DATA                                 = 0x0E2FB, // 14333
        CMSG_WHO                                         = 0x0F2B3, // 14333
        CMSG_WHOIS                                       = 0x026E3, // 14333
        CMSG_WORLD_LOGIN                                 = 0x04011, // 14333
        CMSG_WORLD_STATE_UI_TIMER_UPDATE                 = 0x06222, // 14333
        CMSG_ZONEUPDATE                                  = 0x0AEB7, // 14333

        MSG_AUCTION_HELLO                                = 0x06EAF, // 14333
        MSG_CORPSE_QUERY                                 = 0x03232, // 14333
        MSG_GUILD_BANK_LOG_QUERY                         = 0x072EA, // 14333
        MSG_GUILD_EVENT_LOG_QUERY                        = 0x0AEBE, // 14333
        MSG_GUILD_PERMISSIONS                            = 0x0E22E, // 14333
        MSG_INSPECT_ARENA_TEAMS                          = 0x072A3, // 14333
        MSG_LIST_STABLED_PETS                            = 0x0B272, // 14333
        MSG_MOVE_HEARTBEAT                               = 0x028E3, // 14333
        MSG_MOVE_SET_FACING                              = 0x09848, // 14333
        MSG_MOVE_STOP_TURN                               = 0x03862, // 14333
        MSG_MOVE_TIME_SKIPPED                            = 0x0B2AB, // 14333
        MSG_NOTIFY_PARTY_SQUELCH                         = 0x0766B, // 14333
        MSG_PARTY_ASSIGNMENT                             = 0x0A22A, // 14333
        MSG_PETITION_DECLINE                             = 0x0AE2F, // 14333
        MSG_PETITION_RENAME                              = 0x0FAFA, // 14333
        MSG_PVP_LOG_DATA                                 = 0x05365, // 14333
        MSG_QUERY_GUILD_BANK_TEXT                        = 0x0A236, // 14333
        MSG_QUERY_NEXT_MAIL_TIME                         = 0x0FA62, // 14333
        MSG_QUEST_PUSH_RESULT                            = 0x0BE3A, // 14333
        MSG_RAID_READY_CHECK                             = 0x0A63A, // 14333
        MSG_RAID_READY_CHECK_CONFIRM                     = 0x0AE76, // 14333
        MSG_RAID_READY_CHECK_FINISHED                    = 0x036E6, // 14333
        MSG_RAID_TARGET_UPDATE                           = 0x066FA, // 14333
        MSG_RANDOM_ROLL                                  = 0x0FEFB, // 14333
        MSG_SAVE_GUILD_EMBLEM                            = 0x06A36, // 14333
        MSG_SET_DUNGEON_DIFFICULTY                       = 0x0A23E, // 14333
        MSG_SET_RAID_DIFFICULTY                          = 0x0FA73, // 14333
        MSG_TABARDVENDOR_ACTIVATE                        = 0x0EAEF, // 14333
        MSG_TALENT_WIPE_CONFIRM                          = 0x02EA7, // 14333
        SMSG_ACCOUNT_DATA_TIMES                          = 0x02E3E, // 14333
        SMSG_ACHIEVEMENT_DELETED                         = 0x0EAFE, // 14333
        SMSG_ACHIEVEMENT_EARNED                          = 0x0BAFA, // 14333
        SMSG_ACTION_BUTTONS                              = 0x06EBA, // 14333
        SMSG_ADDON_INFO                                  = 0x06AAE, // 14333
        SMSG_AI_REACTION                                 = 0x0B2EF, // 14333
        SMSG_ALL_ACHIEVEMENT_DATA                        = 0x09B45, // 14333
        SMSG_ARENA_ERROR                                 = 0x0F2FE, // 14333
        SMSG_ARENA_OPPONENT_UPDATE                       = 0x07A6F, // 14333
        SMSG_ARENA_TEAM_CHANGE_FAILED_QUEUED             = 0x0A22B, // 14333
        SMSG_ARENA_TEAM_COMMAND_RESULT                   = 0x08B45, // 14333
        SMSG_ARENA_TEAM_EVENT                            = 0x07273, // 14333
        SMSG_ARENA_TEAM_INVITE                           = 0x0AAEA, // 14333
        SMSG_ARENA_TEAM_QUERY_RESPONSE                   = 0x0FE2F, // 14333
        SMSG_ARENA_TEAM_ROSTER                           = 0x0A276, // 14333
        SMSG_ARENA_TEAM_STATS                            = 0x02EBB, // 14333
        SMSG_ATTACKERSTATEUPDATE                         = 0x0BE26, // 14333
        SMSG_ATTACKSTART                                 = 0x06A22, // 14333
        SMSG_ATTACKSTOP                                  = 0x0E6FF, // 14333
        SMSG_ATTACKSWING_BADFACING                       = 0x0622B, // 14333
        SMSG_ATTACKSWING_CANT_ATTACK                     = 0x0F627, // 14333
        SMSG_ATTACKSWING_DEADTARGET                      = 0x03E67, // 14333
        SMSG_ATTACKSWING_NOTINRANGE                      = 0x0EEE7, // 14333
        SMSG_AUCTION_BIDDER_LIST_RESULT                  = 0x06AB7, // 14333
        SMSG_AUCTION_BIDDER_NOTIFICATION                 = 0x0AE67, // 14333
        SMSG_AUCTION_COMMAND_RESULT                      = 0x0226F, // 14333
        SMSG_AUCTION_LIST_PENDING_SALES                  = 0x0367F, // 14333
        SMSG_AUCTION_LIST_RESULT                         = 0x0EEB7, // 14333
        SMSG_AUCTION_OWNER_LIST_RESULT                   = 0x0E2AB, // 14333
        SMSG_AUCTION_OWNER_NOTIFICATION                  = 0x03E6B, // 14333
        SMSG_AUCTION_REMOVED_NOTIFICATION                = 0x02ABF, // 14333
        SMSG_AURA_UPDATE                                 = 0x02A37, // 14333
        SMSG_AURA_UPDATE_ALL                             = 0x06AA3, // 14333
        SMSG_AUTH_CHALLENGE                              = 0x08C10, // 14333
        SMSG_AUTH_RESPONSE                               = 0x0BEFB, // 14333
        SMSG_AVAILABLE_VOICE_CHANNEL                     = 0x066F3, // 14333
        SMSG_BARBER_SHOP_RESULT                          = 0x0FEEA, // 14333
        SMSG_BATTLEFIELD_LIST                            = 0x05301, // 14333
        SMSG_BATTLEFIELD_MGR_EJECTED                     = 0x01F25, // 14333
        SMSG_BATTLEFIELD_MGR_EJECT_PENDING               = 0x09721, // 14333
        SMSG_BATTLEFIELD_MGR_ENTERED                     = 0x01B41, // 14333
        SMSG_BATTLEFIELD_MGR_ENTRY_INVITE                = 0x0D325, // 14333
        SMSG_BATTLEFIELD_MGR_QUEUE_INVITE                = 0x05B03, // 14333
        SMSG_BATTLEFIELD_MGR_QUEUE_REQUEST_RESPONSE      = 0x01F63, // 14333
        SMSG_BATTLEFIELD_MGR_STATE_CHANGE                = 0x00363, // 14333
        SMSG_BATTLEFIELD_STATUS1                         = 0x00B07, // 14333
        SMSG_BATTLEFIELD_STATUS2                         = 0x04B05, // 14333
        SMSG_BATTLEFIELD_STATUS3                         = 0x04F63, // 14333
        SMSG_BATTLEFIELD_STATUS4                         = 0x00303, // 14333
        SMSG_BATTLEGROUND_INFO_THROTTLED                 = 0x0BABF, // 14333
        SMSG_BATTLEGROUND_PLAYER_JOINED                  = 0x05B27, // 14333
        SMSG_BINDPOINTUPDATE                             = 0x07E26, // 14333
        SMSG_BINDZONEREPLY                               = 0x0622E, // 14333
        SMSG_CALENDAR_COMMAND_RESULT                     = 0x0BE2A, // 14333
        SMSG_CANCEL_AUTO_REPEAT                          = 0x0FEA7, // 14333
        SMSG_CANCEL_COMBAT                               = 0x0A2BB, // 14333
        SMSG_CAST_FAILED                                 = 0x0B626, // 14333
        SMSG_CHANNEL_LIST                                = 0x07E77, // 14333
        SMSG_CHANNEL_MEMBER_COUNT                        = 0x0FAF7, // 14333
        SMSG_CHANNEL_NOTIFY                              = 0x026B6, // 14333
        SMSG_CHARACTER_LOGIN_FAILED                      = 0x03EFA, // 14333
        SMSG_CHAR_CREATE                                 = 0x0B2E3, // 14333
        SMSG_CHAR_DELETE                                 = 0x03E36, // 14333
        SMSG_CHAR_ENUM                                   = 0x0C727, // 14333
        SMSG_CHAT_PLAYER_NOT_FOUND                       = 0x0B2A2, // 14333
        SMSG_CHAT_RESTRICTED                             = 0x07667, // 14333
        SMSG_CHAT_WRONG_FACTION                          = 0x02233, // 14333
        SMSG_CLEAR_TARGET                                = 0x0AE6B, // 14333
        SMSG_CLIENTCACHE_VERSION                         = 0x0A237, // 14333
        SMSG_CLIENT_CONTROL_UPDATE                       = 0x0E267, // 14333
        SMSG_COMBAT_LOG_MULTIPLE                         = 0x0EE77, // 14333
        SMSG_COMMENTATOR_MAP_INFO                        = 0x076F6, // 14333
        SMSG_COMMENTATOR_PLAYER_INFO                     = 0x0E236, // 14333
        SMSG_COMMENTATOR_STATE_CHANGED                   = 0x02AF7, // 14333
        SMSG_COMPLAIN_RESULT                             = 0x07E3E, // 14333
        SMSG_COMPRESSED_MOVES                            = 0x0A6EE, // 14333
        SMSG_COMPRESSED_UPDATE_OBJECT                    = 0x0E23F, // 14333
        SMSG_CONTACT_LIST                                = 0x0BEE3, // 14333
        SMSG_COOLDOWN_CHEAT                              = 0x0A2F3, // 14333
        SMSG_CORPSE_NOT_IN_INSTANCE                      = 0x0BAB7, // 14333
        SMSG_CORPSE_RECLAIM_DELAY                        = 0x0F623, // 14333
        SMSG_CREATURE_QUERY_RESPONSE                     = 0x0AA67, // 14333
        SMSG_CRITERIA_DELETED                            = 0x0F227, // 14333
        SMSG_CRITERIA_UPDATE                             = 0x0A2F7, // 14333
        SMSG_CROSSED_INEBRIATION_THRESHOLD               = 0x026FF, // 14333
        SMSG_DAMAGE_CALC_LOG                             = 0x06AEF, // 14333
        SMSG_DANCE_QUERY_RESPONSE                        = 0x03EFB, // 14333
        SMSG_DEATH_RELEASE_LOC                           = 0x0B27B, // 14333
        SMSG_DEFENSE_MESSAGE                             = 0x0F6B6, // 14333
        SMSG_DESTROY_OBJECT                              = 0x0FEBE, // 14333
        SMSG_DESTRUCTIBLE_BUILDING_DAMAGE                = 0x0BA6E, // 14333
        SMSG_DISPEL_FAILED                               = 0x0A6F2, // 14333
        SMSG_DUEL_COMPLETE                               = 0x0B6FE, // 14333
        SMSG_DUEL_COUNTDOWN                              = 0x07E73, // 14333
        SMSG_DUEL_REQUESTED                              = 0x0AA6E, // 14333
        SMSG_DUEL_WINNER                                 = 0x03AF2, // 14333
        SMSG_DURABILITY_DAMAGE_DEATH                     = 0x0BEA6, // 14333
        SMSG_ECHO_PARTY_SQUELCH                          = 0x0BE63, // 14333
        SMSG_EMOTE                                       = 0x076FE, // 14333
        SMSG_ENABLE_BARBER_SHOP                          = 0x0367A, // 14333
        SMSG_ENCHANTMENTLOG                              = 0x0A6AE, // 14333
        SMSG_ENVIRONMENTALDAMAGELOG                      = 0x06EE6, // 14333
        SMSG_EQUIPMENT_SET_LIST                          = 0x03E2E, // 14333
        SMSG_EQUIPMENT_SET_SAVED                         = 0x076A6, // 14333
        SMSG_EQUIPMENT_SET_USE_RESULT                    = 0x0727F, // 14333
        SMSG_EXPECTED_SPAM_RECORDS                       = 0x0AEB3, // 14333
        SMSG_EXPLORATION_EXPERIENCE                      = 0x0A66A, // 14333
        SMSG_FEATURE_SYSTEM_STATUS                       = 0x01F61, // 14333
        SMSG_FORCEACTIONSHOW                             = 0x07AEA, // 14333
        SMSG_FORCED_DEATH_UPDATE                         = 0x06ABA, // 14333
        SMSG_FORCE_DISPLAY_UPDATE                        = 0x022AE, // 14333
        SMSG_FORCE_SEND_QUEUED_PACKETS                   = 0x00C10, // 14333
        SMSG_FRIEND_STATUS                               = 0x03EBE, // 14333
        SMSG_GAMEOBJECT_DESPAWN_ANIM                     = 0x032F7, // 14333
        SMSG_GAMEOBJECT_QUERY_RESPONSE                   = 0x0AEBF, // 14333
        SMSG_GAMEOBJECT_RESET_STATE                      = 0x0AAAE, // 14333
        SMSG_GAMESPEED_SET                               = 0x0AAB2, // 14333
        SMSG_GAMETIME_SET                                = 0x0B26F, // 14333
        SMSG_GAMETIME_UPDATE                             = 0x06AFE, // 14333
        SMSG_GMRESPONSE_STATUS_UPDATE                    = 0x04090, // 14333
        SMSG_GM_MESSAGECHAT                              = 0x0A262, // 14333
        SMSG_GODMODE                                     = 0x076E7, // 14333
        SMSG_GOSSIP_COMPLETE                             = 0x0F6A3, // 14333
        SMSG_GOSSIP_MESSAGE                              = 0x062E6, // 14333
        SMSG_GOSSIP_POI                                  = 0x0223A, // 14333
        SMSG_GROUP_CANCEL                                = 0x0A627, // 14333
        SMSG_GROUP_DESTROYED                             = 0x06AF6, // 14333
        SMSG_GROUP_JOINED_BATTLEGROUND                   = 0x08707, // 14333
        SMSG_GROUP_LIST                                  = 0x0BEB3, // 14333
        SMSG_GROUP_SET_LEADER                            = 0x03A63, // 14333
        SMSG_GROUP_UNINVITE                              = 0x0BE6B, // 14333
        SMSG_GUILD_BANK_LIST                             = 0x0EA6A, // 14333
        SMSG_GUILD_COMMAND_RESULT                        = 0x0F26A, // 14333
        SMSG_GUILD_DECLINE                               = 0x07A2F, // 14333
        SMSG_GUILD_EVENT                                 = 0x06672, // 14333
        SMSG_GUILD_INFO                                  = 0x03EAF, // 14333
        SMSG_GUILD_INVITE                                = 0x09F65, // 14333
        SMSG_GUILD_NEWS_UPDATE                           = 0x08F41, // 14333
        SMSG_GUILD_QUERY_RESPONSE                        = 0x076E3, // 14333
        SMSG_GUILD_RANK                                  = 0x00F05, // 14333
        SMSG_GUILD_REWARDS_LIST                          = 0x0C303, // 14333
        SMSG_GUILD_ROSTER                                = 0x01B47, // 14333
        SMSG_GUILD_TRADESKILL_UPDATE                     = 0x00343, // 14333
        SMSG_INITIALIZE_FACTIONS                         = 0x03A2A, // 14333
        SMSG_INITIAL_SPELLS                              = 0x0F6AE, // 14333
        SMSG_INIT_CURRENCY                               = 0x0C343, // 14333
        SMSG_INIT_WORLD_STATES                           = 0x07EB7, // 14333
        SMSG_INSPECT                                     = 0x0BA7E, // 14333
        SMSG_INSPECT_HONOR_STATS                         = 0x0CF21, // 14333
        SMSG_INSPECT_TALENT                              = 0x0EAF7, // 14333
        SMSG_INSTANCE_RESET                              = 0x0B6B3, // 14333
        SMSG_INSTANCE_RESET_FAILED                       = 0x0326B, // 14333
        SMSG_INSTANCE_SAVE_CREATED                       = 0x0AE2B, // 14333
        SMSG_INVALIDATE_DANCE                            = 0x022AA, // 14333
        SMSG_INVALIDATE_PLAYER                           = 0x0A2FF, // 14333
        SMSG_INVENTORY_CHANGE_FAILURE                    = 0x036A2, // 14333
        SMSG_ITEM_COOLDOWN                               = 0x0F6FE, // 14333
        SMSG_ITEM_NAME_QUERY_RESPONSE                    = 0x0FA67, // 14333
        SMSG_ITEM_PUSH_RESULT                            = 0x0A6A3, // 14333
        SMSG_ITEM_REFUND_INFO_RESPONSE                   = 0x0DB03, // 14333
        SMSG_ITEM_REFUND_RESULT                          = 0x08765, // 14333
        SMSG_ITEM_TEXT_QUERY_RESPONSE                    = 0x07A3E, // 14333
        SMSG_JOINED_BATTLEGROUND_QUEUE                   = 0x0DB01, // 14333
        SMSG_LEARNED_DANCE_MOVES                         = 0x0A6EB, // 14333
        SMSG_LEARNED_SPELL                               = 0x03626, // 14333
        SMSG_LEVELUP_INFO                                = 0x0E2AE, // 14333
        SMSG_LFG_DISABLED                                = 0x0AEFF, // 14333
        SMSG_LFG_JOIN_RESULT                             = 0x0366A, // 14333
        SMSG_LFG_OFFER_CONTINUE                          = 0x0AAFE, // 14333
        SMSG_LFG_OPEN_FROM_GOSSIP                        = 0x0AEFA, // 14333
        SMSG_LFG_PARTY_INFO                              = 0x0AEAA, // 14333
        SMSG_LFG_PLAYER_REWARD                           = 0x022B6, // 14333
        SMSG_LFG_QUEUE_STATUS                            = 0x06E76, // 14333
        SMSG_LFG_ROLE_CHECK_UPDATE                       = 0x026A3, // 14333
        SMSG_LFG_TELEPORT_DENIED                         = 0x0E6B3, // 14333
        SMSG_LFG_UPDATE_PARTY                            = 0x0666E, // 14333
        SMSG_LFG_UPDATE_PLAYER                           = 0x07A27, // 14333
        SMSG_LOGIN_SETTIMESPEED                          = 0x0766F, // 14333
        SMSG_LOGIN_VERIFY_WORLD                          = 0x0BA77, // 14333
        SMSG_LOGOUT_CANCEL_ACK                           = 0x0AA37, // 14333
        SMSG_LOGOUT_COMPLETE                             = 0x0A27F, // 14333
        SMSG_LOGOUT_RESPONSE                             = 0x062BA, // 14333
        SMSG_LOG_XPGAIN                                  = 0x0EE7A, // 14333
        SMSG_LOOT_ALL_PASSED                             = 0x07222, // 14333
        SMSG_LOOT_CLEAR_MONEY                            = 0x0AABA, // 14333
        SMSG_LOOT_ITEM_NOTIFY                            = 0x0FEF7, // 14333
        SMSG_LOOT_LIST                                   = 0x0B2AB, // 14333
        SMSG_LOOT_MASTER_LIST                            = 0x0A2BE, // 14333
        SMSG_LOOT_MONEY_NOTIFY                           = 0x0B637, // 14333
        SMSG_LOOT_RELEASE_RESPONSE                       = 0x0F66E, // 14333
        SMSG_LOOT_REMOVED                                = 0x0327F, // 14333
        SMSG_LOOT_RESPONSE                               = 0x0F663, // 14333
        SMSG_LOOT_ROLL                                   = 0x06E33, // 14333
        SMSG_LOOT_ROLL_WON                               = 0x02AAA, // 14333
        SMSG_LOOT_SLOT_CHANGED                           = 0x02EFB, // 14333
        SMSG_LOOT_START_ROLL                             = 0x0722A, // 14333
        SMSG_MAIL_LIST_RESULT                            = 0x0F63A, // 14333
        SMSG_MEETINGSTONE_COMPLETE                       = 0x0FA6A, // 14333
        SMSG_MEETINGSTONE_IN_PROGRESS                    = 0x02E7A, // 14333
        SMSG_MEETINGSTONE_MEMBER_ADDED                   = 0x03AEE, // 14333
        SMSG_MEETINGSTONE_SETQUEUE                       = 0x03A3A, // 14333
        SMSG_MESSAGECHAT                                 = 0x06A2A, // 14333
        SMSG_MIRRORIMAGE_DATA                            = 0x02A6B, // 14333
        SMSG_MONSTER_MOVE                                = 0x0AAE6, // 14333
        SMSG_MONSTER_MOVE_TRANSPORT                      = 0x0B2BA, // 14333
        SMSG_MOTD                                        = 0x0E6FB, // 14333
        SMSG_MOUNTSPECIAL_ANIM                           = 0x022F3, // 14333
        SMSG_MULTIPLE_PACKETS                            = 0x02A76, // 14333
        SMSG_NAME_QUERY_RESPONSE                         = 0x0FA67, // 14333
        SMSG_NOTIFICATION                                = 0x076A7, // 14333
        SMSG_NOTIFY_DANCE                                = 0x02632, // 14333
        SMSG_NOTIFY_DEST_LOC_SPELL_CAST                  = 0x0227A, // 14333
        SMSG_NPC_TEXT_UPDATE                             = 0x02AFF, // 14333
        SMSG_OFFER_PETITION_ERROR                        = 0x0267B, // 14333
        SMSG_ON_CANCEL_EXPECTED_RIDE_VEHICLE_AURA        = 0x022BA, // 14333
        SMSG_PAGE_TEXT_QUERY_RESPONSE                    = 0x0762F, // 14333
        SMSG_PARTYKILLLOG                                = 0x03276, // 14333
        SMSG_PARTY_COMMAND_RESULT                        = 0x0F2EF, // 14333
        SMSG_PAUSE_MIRROR_TIMER                          = 0x0A2EF, // 14333
        SMSG_PERIODICAURALOG                             = 0x0A2A3, // 14333
        SMSG_PETGODMODE                                  = 0x072FA, // 14333
        SMSG_PETITION_QUERY_RESPONSE                     = 0x03AB7, // 14333
        SMSG_PET_ACTION_FEEDBACK                         = 0x06A7B, // 14333
        SMSG_PET_ACTION_SOUND                            = 0x062FB, // 14333
        SMSG_PET_CAST_FAILED                             = 0x0EAAA, // 14333
        SMSG_PET_DISMISS_SOUND                           = 0x03EF3, // 14333
        SMSG_PET_GUIDS                                   = 0x0EE2F, // 14333
        SMSG_PET_MODE                                    = 0x0EE26, // 14333
        SMSG_PET_NAME_QUERY_RESPONSE                     = 0x07AFA, // 14333
        SMSG_PET_SPELLS                                  = 0x066A3, // 14333
        SMSG_PET_TAME_FAILURE                            = 0x03EB6, // 14333
        SMSG_PET_UPDATE_COMBO_POINTS                     = 0x0A2E6, // 14333
        SMSG_PLAYED_TIME                                 = 0x02EA2, // 14333
        SMSG_PLAYERBINDERROR                             = 0x0A26B, // 14333
        SMSG_PLAYERBOUND                                 = 0x06EAE, // 14333
        SMSG_PLAYER_DIFFICULTY_CHANGE                    = 0x07EAF, // 14333
        SMSG_PLAYER_SKINNED                              = 0x0FAF6, // 14333
        SMSG_PLAYER_VEHICLE_DATA                         = 0x0FA6B, // 14333
        SMSG_PLAY_DANCE                                  = 0x032B3, // 14333
        SMSG_PLAY_TIME_WARNING                           = 0x0EAE6, // 14333
        SMSG_PONG                                        = 0x00C90, // 14333
        SMSG_POWER_UPDATE                                = 0x0B6BE, // 14333
        SMSG_PRE_RESURRECT                               = 0x026EE, // 14333
        SMSG_PROCRESIST                                  = 0x0BAE3, // 14333
        SMSG_QUERY_QUESTS_COMPLETED_RESPONSE             = 0x07AFE, // 14333
        SMSG_QUERY_TIME_RESPONSE                         = 0x03AF3, // 14333
        SMSG_QUESTGIVER_OFFER_REWARD                     = 0x0E6A3, // 14333
        SMSG_QUESTGIVER_QUEST_COMPLETE                   = 0x01303, // 14333
        SMSG_QUESTGIVER_QUEST_DETAILS                    = 0x0F266, // 14333
        SMSG_QUESTGIVER_QUEST_FAILED                     = 0x0E6FE, // 14333
        SMSG_QUESTGIVER_QUEST_LIST                       = 0x07AE6, // 14333
        SMSG_QUESTGIVER_REQUEST_ITEMS                    = 0x03E76, // 14333
        SMSG_QUESTGIVER_STATUS                           = 0x066FB, // 14333
        SMSG_QUESTGIVER_STATUS_MULTIPLE                  = 0x06E3B, // 14333
        SMSG_QUESTLOG_FULL                               = 0x0E263, // 14333
        SMSG_QUESTUPDATE_ADD_KILL                        = 0x0B67A, // 14333
        SMSG_QUESTUPDATE_ADD_PVP_KILL                    = 0x0727E, // 14333
        SMSG_QUESTUPDATE_COMPLETE                        = 0x03A73, // 14333
        SMSG_QUESTUPDATE_FAILED                          = 0x0EAB7, // 14333
        SMSG_QUESTUPDATE_FAILEDTIMER                     = 0x0BAF7, // 14333
        SMSG_QUEST_CONFIRM_ACCEPT                        = 0x022AF, // 14333
        SMSG_QUEST_FORCE_REMOVED                         = 0x02A7A, // 14333
        SMSG_QUEST_POI_QUERY_RESPONSE                    = 0x0663F, // 14333
        SMSG_QUEST_QUERY_RESPONSE                        = 0x0AEE3, // 14333
        SMSG_RAID_INSTANCE_MESSAGE                       = 0x06677, // 14333
        SMSG_READ_ITEM_FAILED                            = 0x06EE7, // 14333
        SMSG_READ_ITEM_OK                                = 0x0B6E7, // 14333
        SMSG_REALM_SPLIT                                 = 0x0692C, // 14333
        SMSG_REAL_GROUP_UPDATE                           = 0x0A66F, // 14333
        SMSG_RECEIVED_MAIL                               = 0x07EEB, // 14333
        SMSG_REDIRECT_CLIENT                             = 0x00410, // 14333
        SMSG_REFER_A_FRIEND_FAILURE                      = 0x066BF, // 14333
        SMSG_REMOVED_SPELL                               = 0x07AF6, // 14333
        SMSG_REPORT_PVP_AFK_RESULT                       = 0x076AA, // 14333
        SMSG_RESURRECT_REQUEST                           = 0x0322E, // 14333
        SMSG_RWHOIS                                      = 0x0E63A, // 14333
        SMSG_SEND_MAIL_RESULT                            = 0x0A6FE, // 14333
        SMSG_SEND_UNLEARN_SPELLS                         = 0x0AAE2, // 14333
        SMSG_SERVERTIME                                  = 0x07236, // 14333
        SMSG_SERVER_FIRST_ACHIEVEMENT                    = 0x0EE7F, // 14333
        SMSG_SERVER_MESSAGE                              = 0x0E62F, // 14333
        SMSG_SET_FACTION_ATWAR                           = 0x07ABE, // 14333
        SMSG_SET_FACTION_STANDING                        = 0x026EB, // 14333
        SMSG_SET_FACTION_VISIBLE                         = 0x06EEA, // 14333
        SMSG_SET_FLAT_SPELL_MODIFIER                     = 0x0B6EB, // 14333
        SMSG_SET_PCT_SPELL_MODIFIER                      = 0x0FAAF, // 14333
        SMSG_SET_PHASE_SHIFT                             = 0x0DB05, // 14333
        SMSG_SET_PROFICIENCY                             = 0x07EE6, // 14333
        SMSG_SET_PROJECTILE_POSITION                     = 0x0FA23, // 14333
        SMSG_SPELLBREAKLOG                               = 0x0EEFE, // 14333
        SMSG_SPELLDAMAGESHIELD                           = 0x076EE, // 14333
        SMSG_SPELLENERGIZELOG                            = 0x07A2A, // 14333
        SMSG_SPELLHEALLOG                                = 0x0F673, // 14333
        SMSG_SPELLINSTAKILLLOG                           = 0x062FE, // 14333
        SMSG_SPELLLOGEXECUTE                             = 0x0E223, // 14333
        SMSG_SPELLLOGMISS                                = 0x07623, // 14333
        SMSG_SPELLNONMELEEDAMAGELOG                      = 0x0B2AE, // 14333
        SMSG_SPELLORDAMAGE_IMMUNE                        = 0x0E622, // 14333
        SMSG_SPELL_COOLDOWN                              = 0x07277, // 14333
        SMSG_SPELL_DELAYED                               = 0x0B636, // 14333
        SMSG_SPELL_FAILED_OTHER                          = 0x02EE7, // 14333
        SMSG_SPELL_FAILURE                               = 0x022FB, // 14333
        SMSG_SPELL_GO                                    = 0x02A27, // 14333
        SMSG_SPELL_START                                 = 0x0A632, // 14333
        SMSG_SPELL_UPDATE_CHAIN_TARGETS                  = 0x06666, // 14333
        SMSG_STABLE_RESULT                               = 0x0EA36, // 14333
        SMSG_STANDSTATE_CHANGE_FAILURE_OBSOLETE          = 0x0E6FF, // 14333
        SMSG_STANDSTATE_UPDATE                           = 0x0E2F6, // 14333
        SMSG_START_MIRROR_TIMER                          = 0x0AAA7, // 14333
        SMSG_STOP_DANCE                                  = 0x072BF, // 14333
        SMSG_STOP_MIRROR_TIMER                           = 0x0B63E, // 14333
        SMSG_SUMMON_REQUEST                              = 0x022FF, // 14333
        SMSG_SUPERCEDED_SPELL                            = 0x03E3E, // 14333
        SMSG_TALENTS_INFO                                = 0x0BABF, // 14333
        SMSG_TAXINODE_STATUS                             = 0x0226A, // 14333
        SMSG_TEXT_EMOTE                                  = 0x026EF, // 14333
        SMSG_THREAT_CLEAR                                = 0x03A76, // 14333
        SMSG_THREAT_REMOVE                               = 0x07626, // 14333
        SMSG_TITLE_EARNED                                = 0x0AEBA, // 14333
        SMSG_TRADE_STATUS                                = 0x0DB61, // 14333
        SMSG_TRADE_STATUS_EXTENDED                       = 0x0DF27, // 14333
        SMSG_TRANSFER_ABORTED                            = 0x066AF, // 14333
        SMSG_TRANSFER_PENDING                            = 0x026EA, // 14333
        SMSG_TRIGGER_CINEMATIC                           = 0x0A2FE, // 14333
        SMSG_TUTORIAL_FLAGS                              = 0x07E72, // 14333
        SMSG_UNIT_SPELLCAST_START                        = 0x0BAAA, // 14333
        SMSG_UPDATE_ACCOUNT_DATA                         = 0x0AA66, // 14333
        SMSG_UPDATE_ACCOUNT_DATA_COMPLETE                = 0x06A2F, // 14333
        SMSG_UPDATE_COMBO_POINTS                         = 0x0BE73, // 14333
        SMSG_UPDATE_CURRENCY                             = 0x0D323, // 14333
        SMSG_UPDATE_INSTANCE_ENCOUNTER_UNIT              = 0x03EF2, // 14333
        SMSG_UPDATE_INSTANCE_OWNERSHIP                   = 0x07A2B, // 14333
        SMSG_UPDATE_LAST_INSTANCE                        = 0x0AA32, // 14333
        SMSG_UPDATE_LFG_LIST                             = 0x0EE37, // 14333
        SMSG_UPDATE_OBJECT                               = 0x072A7, // 14333
        SMSG_USERLIST_ADD                                = 0x0B67F, // 14333
        SMSG_USERLIST_REMOVE                             = 0x0E2E6, // 14333
        SMSG_USERLIST_UPDATE                             = 0x0BAE7, // 14333
        SMSG_VOICE_CHAT_STATUS                           = 0x02EAA, // 14333
        SMSG_VOICE_PARENTAL_CONTROLS                     = 0x0B6EA, // 14333
        SMSG_VOICE_SESSION_LEAVE                         = 0x0EA27, // 14333
        SMSG_VOICE_SESSION_ROSTER_UPDATE                 = 0x0F666, // 14333
        SMSG_VOICE_SET_TALKER_MUTED                      = 0x0B6A2, // 14333
        SMSG_WARDEN_DATA                                 = 0x07A36, // 14333
        SMSG_WHO                                         = 0x0223B, // 14333
        SMSG_WHOIS                                       = 0x0AA76, // 14333
        SMSG_ZONE_UNDER_ATTACK                           = 0x0FE72, // 14333

            NUM_MSG_TYPES                                   = 0xFFFF
            */
    };
}
